### ISSUE TITLE
pip crashing in pretix 2.1.0 to dev

### ISSUE THREAD

**Issue by samirfor** [pretix/pretix#1050]
```bash
[root@fl005 pretix]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core)
[root@fl005 pretix]# python3.6 -m venv env
[root@fl005 pretix]# source env/bin/activate
(env) [root@fl005 pretix]# pip -V
pip 18.1 from /opt/tik/pretix/env/lib64/python3.6/site-packages/pip (python 3.6)
(env) [root@fl005 pretix]# python -V
Python 3.6.5
(env) [root@fl005 pretix]# pip install -U pip setuptools
Cache entry deserialization failed, entry ignored
Collecting pip
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl
Cache entry deserialization failed, entry ignored
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/96/06/c8ee69628191285ddddffb277bd5abdf769166e7a14b867c2a172f0175b1/setuptools-40.4.3-py2.py3-none-any.whl
Installing collected packages: pip, setuptools
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
  Found existing installation: setuptools 39.0.1
    Uninstalling setuptools-39.0.1:
      Successfully uninstalled setuptools-39.0.1
Successfully installed pip-18.1 setuptools-40.4.3

(env) [root@fl005 src]# pip install -Ur requirements.txt requirements/dev.txt 
Invalid requirement: 'requirements/dev.txt'
It looks like a path. It does exist. The argument you provided (requirements/dev.txt) appears to be a requirements file. If that is the case, use the '-r' flag to install the packages specified within it.
(env) [root@fl005 src]# pip install -Ur requirements.txt -r requirements/dev.txt 
Collecting Django<2.2,>=2.1 (from -r requirements/production.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/32/ab/22530cc1b2114e6067eece94a333d6c749fa1c56a009f0721e51c181ea53/Django-2.1.2-py3-none-any.whl
Collecting djangorestframework==3.8.* (from -r requirements/production.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/90/30/ad1148098ff0c375df2a30cc4494ed953cf7551fc1ecec30fc951c712d20/djangorestframework-3.8.2-py2.py3-none-any.whl
Collecting python-dateutil (from -r requirements/production.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting pytz (from -r requirements/production.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Collecting django-bootstrap3==10.0.* (from -r requirements/production.txt (line 6))
Collecting django-formset-js-improved==0.5.0.2 (from -r requirements/production.txt (line 7))
Collecting django-compressor==2.2.* (from -r requirements/production.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/02/7b/deb4605f95bcefb9760ff130533553230a1c25f4d383ed0735b075d71b29/django_compressor-2.2-py2.py3-none-any.whl
Collecting django-hierarkey==1.0.*,>=1.0.3 (from -r requirements/production.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/20/71/749a786b8e7680663f52f99980620176cf23be9b7e94f2ad2b81e4fb88fe/django_hierarkey-1.0.3-py3-none-any.whl
Collecting django-filter==2.0.* (from -r requirements/production.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/6a/8b/8517167a0adc45ce94d0873efb9487dd4cdeff7e10f96e837ad3d58f5837/django_filter-2.0.0-py3-none-any.whl
Collecting reportlab==3.5.* (from -r requirements/production.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/b9/13/caf6e87cb74c4a1e5642c55d90a205e0186ad123f3fb093e91711097c8f0/reportlab-3.5.9-cp36-cp36m-manylinux1_x86_64.whl
Collecting PyPDF2==1.26.* (from -r requirements/production.txt (line 12))
Collecting Pillow (from -r requirements/production.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/62/94/5430ebaa83f91cc7a9f687ff5238e26164a779cca2ef9903232268b0a318/Pillow-5.3.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting django-libsass (from -r requirements/production.txt (line 14))
Collecting libsass (from -r requirements/production.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/76/6e/396a08fecfb456324ecee744cccd230c04d1fbb0d9883f88570bf86e23cd/libsass-0.15.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting django-otp==0.4.* (from -r requirements/production.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/a6/59/7b60245c98a157ee5cb2dc52493f69d4a772fe867bfff2b5a11d6fee1225/django_otp-0.4.3-py2.py3-none-any.whl
Collecting python-u2flib-server==4.* (from -r requirements/production.txt (line 17))
Collecting django-formtools==2.1 (from -r requirements/production.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/97/3f/b8e04c41c028d5cdad651393abea1f686d846c717d8ab5d5ebe2974f711c/django_formtools-2.1-py2.py3-none-any.whl
Collecting celery<4.2.0,>=4.1.1 (from -r requirements/production.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/99/fa/4049b26bfe71992ecf979acd39b87e55b493608613054089d975418015b7/celery-4.1.1-py2.py3-none-any.whl
Collecting kombu==4.2.* (from -r requirements/production.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/97/61/65838c7da048e56d549e358ac19c0979c892e17dc6186610c49531d35b70/kombu-4.2.1-py2.py3-none-any.whl
Collecting django-statici18n==1.8.* (from -r requirements/production.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/f5/61/7261847d3dbe6bb23aa635821caf9e5cde7a86db233edf6fc8b1a5fc7417/django_statici18n-1.8.2-py2.py3-none-any.whl
Collecting inlinestyler==0.2.* (from -r requirements/production.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/f8/3a/4f20eccc1673291be57653dc2bfa117fee2dfcbf0e9a5bc0c6862885d506/inlinestyler-0.2.5-py2.py3-none-any.whl
Collecting BeautifulSoup4 (from -r requirements/production.txt (line 23))
  Using cached https://files.pythonhosted.org/packages/21/0a/47fdf541c97fd9b6a610cb5fd518175308a7cc60569962e776ac52420387/beautifulsoup4-4.6.3-py3-none-any.whl
Collecting slimit (from -r requirements/production.txt (line 24))
Collecting lxml (from -r requirements/production.txt (line 25))
  Using cached https://files.pythonhosted.org/packages/03/a4/9eea8035fc7c7670e5eab97f34ff2ef0ddd78a491bf96df5accedb0e63f5/lxml-4.2.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting static3==0.7.* (from -r requirements/production.txt (line 26))
Collecting dj-static (from -r requirements/production.txt (line 27))
Collecting csscompressor (from -r requirements/production.txt (line 28))
Collecting django-markup (from -r requirements/production.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/2e/66/8cc980bac5156c229e0b78b7393853fda6661e779f5bec7de303503c6fc6/django_markup-1.3-py2.py3-none-any.whl
Collecting markdown<=2.2 (from -r requirements/production.txt (line 30))
Collecting bleach==2.* (from -r requirements/production.txt (line 31))
  Using cached https://files.pythonhosted.org/packages/94/aa/0f7ce53f8688bb9f80c0cffacc3964ddfe08321c509c0bfe5062848951f9/bleach-2.1.4-py2.py3-none-any.whl
Collecting raven (from -r requirements/production.txt (line 32))
  Using cached https://files.pythonhosted.org/packages/11/3a/b3e46b279b8bdd9eb55857d0e95044cad31732c80f628bb75e1e9e881a32/raven-6.9.0-py2.py3-none-any.whl
Collecting babel (from -r requirements/production.txt (line 33))
  Using cached https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl
Collecting django-i18nfield>=1.4.0 (from -r requirements/production.txt (line 34))
  Using cached https://files.pythonhosted.org/packages/7f/a7/0636a758b77be56da680682257a9f5266d5e5f3fe8f7a4d4b56de5eabd09/django_i18nfield-1.4.0-py3-none-any.whl
Collecting django-hijack<2.2.0,>=2.1.10 (from -r requirements/production.txt (line 35))
Collecting django-oauth-toolkit==1.2.* (from -r requirements/production.txt (line 36))
  Using cached https://files.pythonhosted.org/packages/57/6a/42c5c2ac5bcae09559f29ab0ff8afb2ee94ca9a0816eae0b475944f86684/django_oauth_toolkit-1.2.0-py2.py3-none-any.whl
Collecting stripe==2.0.* (from -r requirements/production.txt (line 38))
  Using cached https://files.pythonhosted.org/packages/8a/ec/f69400cc3f956b6e0e0d28066e029ea78349a8887bc9db6ee00a0fe95694/stripe-2.0.3-py2.py3-none-any.whl
Collecting paypalrestsdk==1.13.* (from -r requirements/production.txt (line 40))
Collecting pycparser==2.13 (from -r requirements/production.txt (line 41))
Collecting chardet<3.1.0,>=3.0.2 (from -r requirements/production.txt (line 43))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting mt-940==3.2 (from -r requirements/production.txt (line 44))
Collecting vobject==0.9.* (from -r requirements/production.txt (line 45))
Collecting pycountry (from -r requirements/production.txt (line 46))
  Using cached https://files.pythonhosted.org/packages/c5/c0/8ce9d2b55347867900edbe4d18f790571130c16f882b4891a0f08627dcdc/pycountry-18.5.26-py2.py3-none-any.whl
Collecting django-countries (from -r requirements/production.txt (line 47))
  Using cached https://files.pythonhosted.org/packages/53/9a/010dde87cca2256616b54fba3b2cdd8cf54e08dcf85536ef56e5b9472bc9/django_countries-5.3.2-py2.py3-none-any.whl
Collecting pyuca (from -r requirements/production.txt (line 48))
  Using cached https://files.pythonhosted.org/packages/98/88/aeeee34d88f841aca712a8c18fbd62a33eaad8f2dbe535e87f3c829b02f9/pyuca-1.2-py2.py3-none-any.whl
Collecting defusedcsv>=1.0.1 (from -r requirements/production.txt (line 49))
  Using cached https://files.pythonhosted.org/packages/83/8b/5f512c27ec12eadfa74e89dbca1ec78b1a98dbc6cf0e488539cf727a50b9/defusedcsv-1.0.1-py3-none-any.whl
Collecting vat_moss==0.11.0 (from -r requirements/production.txt (line 50))
Collecting idna==2.6 (from -r requirements/production.txt (line 51))
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
Collecting django-redis==4.8.* (from -r requirements/production.txt (line 52))
  Using cached https://files.pythonhosted.org/packages/2f/98/f33d235cb0d6581137e618ec032daebffa65f8712930aae4158274d87b09/django_redis-4.8.0-py2.py3-none-any.whl
Collecting redis==2.10.5 (from -r requirements/production.txt (line 53))
  Using cached https://files.pythonhosted.org/packages/08/c1/457428f7507e27ba7144758a7b716ea35766e6d602f4a0c16e443ab3d381/redis-2.10.5-py2.py3-none-any.whl
Collecting django-debug-toolbar==1.9.1 (from -r requirements/dev.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/b2/ff/eb95539d31b3f3c12803c8f18cefe7f9e6f7281b059a36dbc9ee9b52c558/django_debug_toolbar-1.9.1-py2.py3-none-any.whl
Collecting sqlparse==0.2.1 (from -r requirements/dev.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/18/3f/6f7182f040a083f9d8645dd28cb4ebfa6f90aca1bd6f61b36259966d148b/sqlparse-0.2.1-py2.py3-none-any.whl
Collecting pep8==1.5.7 (from -r requirements/dev.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/e2/3a/fb53887b208e7e444c13b59244fcac4ef923678e6ae33e7fc71391f37b62/pep8-1.5.7-py2.py3-none-any.whl
Collecting pyflakes==1.5.0 (from -r requirements/dev.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/27/49/924098b3b85c286696f37e014475d79471ffc44509613af420645a3c12cb/pyflakes-1.5.0-py2.py3-none-any.whl
Collecting pep8-naming (from -r requirements/dev.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/39/bb/a34544c789e7e5458ed2db6cbd1c8e227bb01e4ce03a0b15ec4ec93e486d/pep8_naming-0.7.0-py2.py3-none-any.whl
Collecting flake8 (from -r requirements/dev.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/b9/dc/14e9d94c770b8c4ef584e906c7583e74864786a58d47de101f2767d50c0b/flake8-3.5.0-py2.py3-none-any.whl
Collecting codecov (from -r requirements/dev.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/8b/28/4c1950a61c3c5786f0f34d643d0d28ec832433c9a7c0bd157690d4eb1d5f/codecov-2.0.15-py2.py3-none-any.whl
Collecting coverage (from -r requirements/dev.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/3d/a0/b12090c40e0b8196b973962ec71c1c541a6c04af58ba5ad85683b3de251a/coverage-4.5.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pytest==3.6.* (from -r requirements/dev.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/d8/e9/73246a565c34c5f203dd78bc2382e0e93aa7a249cdaeba709099eb1bc701/pytest-3.6.4-py2.py3-none-any.whl
Collecting pytest-django (from -r requirements/dev.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/6e/fe/6e5b43eac75c617cd9383ce82dd76d08fa198a770b06986951b3086980c9/pytest_django-3.4.3-py2.py3-none-any.whl
Collecting isort (from -r requirements/dev.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/1f/2c/22eee714d7199ae0464beda6ad5fedec8fee6a2f7ffd1e8f1840928fe318/isort-4.3.4-py3-none-any.whl
Collecting pytest-rerunfailures==4.* (from -r requirements/dev.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/ca/54/a1085885776be66eecc8012f40807e5fbacb9383e7fede2714b3346fe767/pytest_rerunfailures-4.2-py2.py3-none-any.whl
Collecting pytest-mock==1.6.* (from -r requirements/dev.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/14/92/0791274b2964fa8a568c84f7cdff8e218dfa6c2e1bc2ebd2d7ae0b69bc4c/pytest_mock-1.6.3-py2.py3-none-any.whl
Collecting pytest-cache (from -r requirements/dev.txt (line 15))
Collecting pytest-sugar (from -r requirements/dev.txt (line 16))
Collecting responses (from -r requirements/dev.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/d9/a2/1cf64651ca0837ea627fbf0455231611bec85dbb7a9ffe761365950cabe5/responses-0.9.0-py2.py3-none-any.whl
Collecting potypo (from -r requirements/dev.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/94/3b/e36e09cfeab743de3ca26373d15599748c4aa9251d86f315b60f0da44d47/potypo-0.0.2-py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->-r requirements/production.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting django-jquery-js (from django-formset-js-improved==0.5.0.2->-r requirements/production.txt (line 7))
Collecting django-appconf>=1.0 (from django-compressor==2.2.*->-r requirements/production.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/5b/78/726cdf3e04660560cf25f9def95b8f2736310c581dabed9adfe60154a9f8/django_appconf-1.0.2-py2.py3-none-any.whl
Collecting rcssmin==1.0.6 (from django-compressor==2.2.*->-r requirements/production.txt (line 8))
Collecting rjsmin==1.0.12 (from django-compressor==2.2.*->-r requirements/production.txt (line 8))
Collecting cryptography>=1.2 (from python-u2flib-server==4.*->-r requirements/production.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/59/32/92cade62c645756a83598edf56289e9b19aae5370642a7ce690cd06bc72f/cryptography-2.3.1-cp34-abi3-manylinux1_x86_64.whl
Collecting billiard<3.6.0,>=3.5.0.2 (from celery<4.2.0,>=4.1.1->-r requirements/production.txt (line 19))
Collecting amqp<3.0,>=2.1.4 (from kombu==4.2.*->-r requirements/production.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/7f/cf/12d4611fc67babd4ae250c9e8249c5650ae1933395488e9e7e3562b4ff24/amqp-2.3.2-py2.py3-none-any.whl
Collecting requests>=1.0.0 (from inlinestyler==0.2.*->-r requirements/production.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting cssutils (from inlinestyler==0.2.*->-r requirements/production.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/6b/15/a9fb9010f58d1c55dd0b7779db2334feb9a572d407024f39a60f44293861/cssutils-1.0.2-py3-none-any.whl
Collecting ply>=3.4 (from slimit->-r requirements/production.txt (line 24))
  Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
Collecting html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre (from bleach==2.*->-r requirements/production.txt (line 31))
  Using cached https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl
Collecting django-compat>=1.0.14 (from django-hijack<2.2.0,>=2.1.10->-r requirements/production.txt (line 35))
Collecting oauthlib>=2.0.3 (from django-oauth-toolkit==1.2.*->-r requirements/production.txt (line 36))
  Using cached https://files.pythonhosted.org/packages/e6/d1/ddd9cfea3e736399b97ded5c2dd62d1322adef4a72d816f1ed1049d6a179/oauthlib-2.1.0-py2.py3-none-any.whl
Collecting pyopenssl>=0.15 (from paypalrestsdk==1.13.*->-r requirements/production.txt (line 40))
  Using cached https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl
Collecting pyyaml (from mt-940==3.2->-r requirements/production.txt (line 44))
Collecting flake8-polyfill<2,>=1.0.2 (from pep8-naming->-r requirements/dev.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/86/b5/a43fed6fd0193585d17d6faa7b85317d4461f694aaed546098c69f856579/flake8_polyfill-1.0.2-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8->-r requirements/dev.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8->-r requirements/dev.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/e4/81/78fe51eb4038d1388b7217dd63770b0f428370207125047312886c923b26/pycodestyle-2.3.1-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest==3.6.*->-r requirements/dev.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/3e/c7/3da685ef117d42ac8d71af525208759742dd235f8094221fdaafcd3dba8f/py-1.7.0-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest==3.6.*->-r requirements/dev.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/79/b1/eace304ef66bd7d3d8b2f78cc374b73ca03bc53664d78151e9df3b3996cc/more_itertools-4.3.0-py3-none-any.whl
Collecting attrs>=17.4.0 (from pytest==3.6.*->-r requirements/dev.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Collecting pluggy<0.8,>=0.5 (from pytest==3.6.*->-r requirements/dev.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/f5/f1/5a93c118663896d83f7bcbfb7f657ce1d0c0d617e6b4a443a53abcc658ca/pluggy-0.7.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: setuptools in /opt/tik/pretix/env/lib/python3.6/site-packages (from pytest==3.6.*->-r requirements/dev.txt (line 10)) (40.4.3)
Collecting atomicwrites>=1.0 (from pytest==3.6.*->-r requirements/dev.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/3a/9a/9d878f8d885706e2530402de6417141129a943802c084238914fa6798d97/atomicwrites-1.2.1-py2.py3-none-any.whl
Collecting execnet>=1.1.dev1 (from pytest-cache->-r requirements/dev.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/f9/76/3343e69a2a1602052f587898934e5fea395d22310d39c07955596597227c/execnet-1.5.0-py2.py3-none-any.whl
Collecting termcolor>=1.1.0 (from pytest-sugar->-r requirements/dev.txt (line 16))
Collecting cookies (from responses->-r requirements/dev.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/6a/60/557f84aa2db629e5124aa05408b975b1b5d0e1cec16cde0bfa06aae097d3/cookies-2.2.1-py2.py3-none-any.whl
Collecting polib (from potypo->-r requirements/dev.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/30/a2/e407c3b00cace3d7fc8df14d364deeecfeb96044e1a317de583bc26eae58/polib-1.1.0-py2.py3-none-any.whl
Collecting pyenchant (from potypo->-r requirements/dev.txt (line 18))
Collecting asn1crypto>=0.21.0 (from cryptography>=1.2->python-u2flib-server==4.*->-r requirements/production.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.7 (from cryptography>=1.2->python-u2flib-server==4.*->-r requirements/production.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting vine>=1.1.3 (from amqp<3.0,>=2.1.4->kombu==4.2.*->-r requirements/production.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/10/50/5b1ebe42843c19f35edb15022ecae339fbec6db5b241a7a13c924dabf2a3/vine-1.1.4-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests>=1.0.0->inlinestyler==0.2.*->-r requirements/production.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=1.0.0->inlinestyler==0.2.*->-r requirements/production.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl
Collecting webencodings (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach==2.*->-r requirements/production.txt (line 31))
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Collecting apipkg>=1.4 (from execnet>=1.1.dev1->pytest-cache->-r requirements/dev.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/67/08/4815a09603fc800209431bec5b8bd2acf2f95abdfb558a44a42507fb94da/apipkg-1.5-py2.py3-none-any.whl
Installing collected packages: pytz, Django, djangorestframework, six, python-dateutil, django-bootstrap3, django-jquery-js, django-formset-js-improved, django-appconf, rcssmin, rjsmin, django-compressor, django-hierarkey, django-filter, Pillow, reportlab, PyPDF2, libsass, django-libsass, django-otp, asn1crypto, pycparser, cffi, idna, cryptography, python-u2flib-server, django-formtools, vine, amqp, kombu, billiard, celery, django-statici18n, urllib3, chardet, certifi, requests, lxml, cssutils, inlinestyler, BeautifulSoup4, ply, slimit, static3, dj-static, csscompressor, django-markup, markdown, webencodings, html5lib, bleach, raven, babel, django-i18nfield, django-compat, django-hijack, oauthlib, django-oauth-toolkit, stripe, pyopenssl, paypalrestsdk, pyyaml, mt-940, vobject, pycountry, django-countries, pyuca, defusedcsv, vat-moss, redis, django-redis, sqlparse, django-debug-toolbar, pep8, pyflakes, mccabe, pycodestyle, flake8, flake8-polyfill, pep8-naming, coverage, codecov, py, more-itertools, attrs, pluggy, atomicwrites, pytest, pytest-django, isort, pytest-rerunfailures, pytest-mock, apipkg, execnet, pytest-cache, termcolor, pytest-sugar, cookies, responses, polib, pyenchant, potypo
Exception:
Traceback (most recent call last):
  File "/opt/tik/pretix/env/lib64/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/opt/tik/pretix/env/lib64/python3.6/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/opt/tik/pretix/env/lib64/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/opt/tik/pretix/env/lib64/python3.6/site-packages/pip/_internal/req/req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/opt/tik/pretix/env/lib64/python3.6/site-packages/pip/_internal/req/req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/opt/tik/pretix/env/lib64/python3.6/site-packages/pip/_internal/wheel.py", line 215, in move_wheel_files
    prefix=prefix,
  File "/opt/tik/pretix/env/lib64/python3.6/site-packages/pip/_internal/locations.py", line 153, in distutils_scheme
    d.parse_config_files()
  File "/usr/lib64/python3.6/distutils/dist.py", line 395, in parse_config_files
    parser.read(filename)
  File "/usr/lib64/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib64/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 886: ordinal not in range(128)
```

What am I doing wrong?
Any tips?

**Comment by raphaelm** [comment]
The bug is probably in one of the packages, but the fix might be just to set an appropriate system locale, e.g.

```export LC_ALL=en_US.UTF-8```

before running the command.
