### ISSUE TITLE
Stripe exceptions in pretix-web log

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1189]
I have noticed these in the pretix-web log..
They show up with every order that is being paid (bancontact, haven't tested others yet)

```
Feb 21 15:04:46 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:46,416 stripe util message='Request to Stripe api' method=post path=https://api.stripe.com/v1/sources
Feb 21 15:04:47 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:47,231 stripe util message='Stripe API response' path=https://api.stripe.com/v1/sources response_code=200
Feb 21 15:04:52 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:52,779 stripe util message='Request to Stripe api' method=get path=https://api.stripe.com/v1/sources/src_1E6J6RJW4tzPOZOnAQbMvq6n
Feb 21 15:04:53 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:53,272 stripe util message='Request to Stripe api' method=get path=https://api.stripe.com/v1/sources/src_1E6J6RJW4tzPOZOnAQbMvq6n
Feb 21 15:04:53 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:53,529 stripe util message='Stripe API response' path=https://api.stripe.com/v1/sources/src_1E6J6RJW4tzPOZOnAQbMvq6n response_code=200
Feb 21 15:04:53 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:53,537 stripe util message='Request to Stripe api' method=post path=https://api.stripe.com/v1/charges
Feb 21 15:04:54 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:54,016 stripe util message='Stripe API response' path=https://api.stripe.com/v1/sources/src_1E6J6RJW4tzPOZOnAQbMvq6n response_code=200
Feb 21 15:04:54 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:54,026 stripe util message='Request to Stripe api' method=post path=https://api.stripe.com/v1/charges
Feb 21 15:04:54 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:54,754 stripe util message='Stripe API response' path=https://api.stripe.com/v1/charges response_code=409
Feb 21 15:04:54 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:54,755 stripe util error_code=idempotency_key_in_use error_message='There is currently another in-progress request using this Idempotent Key (that probably means you submitted twice, and the other request is still going through): 2YAY37src_1E6J6RJW4tzPOZOnAQbMvq6n. Please try again later.' error_param=None error_type=invalid_request_error message='Stripe API error received'
Feb 21 15:04:54 api-vm-default gunicorn[26814]: ERROR 2019-02-21 16:04:54,755 pretix.plugins.stripe payment Stripe error: {'code': 'idempotency_key_in_use', 'message': 'There is currently another in-progress request using this Idempotent Key (that probably means you submitted twice, and the other request is still going through): 2YAY37src_1E6J6RJW4tzPOZOnAQbMvq6n. Please try again later.', 'type': 'invalid_request_error', 'doc_url': 'https://stripe.com/docs/error-codes/idempotency-key-in-use'}
Feb 21 15:04:54 api-vm-default gunicorn[26814]: Traceback (most recent call last):
Feb 21 15:04:54 api-vm-default gunicorn[26814]:   File "/var/pretix/venv/lib/python3.5/site-packages/pretix/plugins/stripe/payment.py", line 313, in _charge_source
Feb 21 15:04:54 api-vm-default gunicorn[26814]:     **params
Feb 21 15:04:54 api-vm-default gunicorn[26814]:   File "/var/pretix/venv/lib/python3.5/site-packages/stripe/api_resources/abstract/createable_api_resource.py", line 17, in create
Feb 21 15:04:54 api-vm-default gunicorn[26814]:     response, api_key = requestor.request('post', url, params, headers)
Feb 21 15:04:54 api-vm-default gunicorn[26814]:   File "/var/pretix/venv/lib/python3.5/site-packages/stripe/api_requestor.py", line 94, in request
Feb 21 15:04:54 api-vm-default gunicorn[26814]:     resp = self.interpret_response(rbody, rcode, rheaders)
Feb 21 15:04:54 api-vm-default gunicorn[26814]:   File "/var/pretix/venv/lib/python3.5/site-packages/stripe/api_requestor.py", line 306, in interpret_response
Feb 21 15:04:54 api-vm-default gunicorn[26814]:     self.handle_error_response(rbody, rcode, resp.data, rheaders)
Feb 21 15:04:54 api-vm-default gunicorn[26814]:   File "/var/pretix/venv/lib/python3.5/site-packages/stripe/api_requestor.py", line 119, in handle_error_response
Feb 21 15:04:54 api-vm-default gunicorn[26814]:     raise err
Feb 21 15:04:54 api-vm-default gunicorn[26814]: stripe.error.APIError: Request req_vSnTuIEKcoRIRn: There is currently another in-progress request using this Idempotent Key (that probably means you submitted twice, and the other request is still going through): 2YAY37src_1E6J6RJW4tzPOZOnAQbMvq6n. Please try again later.
Feb 21 15:04:54 api-vm-default gunicorn[26814]: ERROR 2019-02-21 16:04:54,758 pretix.plugins.stripe views Webhook error
Feb 21 15:04:54 api-vm-default gunicorn[26814]: Traceback (most recent call last):
Feb 21 15:04:54 api-vm-default gunicorn[26814]:   File "/var/pretix/venv/lib/python3.5/site-packages/pretix/plugins/stripe/payment.py", line 313, in _charge_source
Feb 21 15:04:54 api-vm-default gunicorn[26814]:     **params
Feb 21 15:04:54 api-vm-default gunicorn[26814]:   File "/var/pretix/venv/lib/python3.5/site-packages/stripe/api_resources/abstract/createable_api_resource.py", line 17, in create
Feb 21 15:04:54 api-vm-default gunicorn[26814]:     response, api_key = requestor.request('post', url, params, headers)
Feb 21 15:04:54 api-vm-default gunicorn[26814]:   File "/var/pretix/venv/lib/python3.5/site-packages/stripe/api_requestor.py", line 94, in request
Feb 21 15:04:54 api-vm-default gunicorn[26814]:     resp = self.interpret_response(rbody, rcode, rheaders)
Feb 21 15:04:54 api-vm-default gunicorn[26814]:   File "/var/pretix/venv/lib/python3.5/site-packages/stripe/api_requestor.py", line 306, in interpret_response
Feb 21 15:04:54 api-vm-default gunicorn[26814]:     self.handle_error_response(rbody, rcode, resp.data, rheaders)
Feb 21 15:04:54 api-vm-default gunicorn[26814]:   File "/var/pretix/venv/lib/python3.5/site-packages/stripe/api_requestor.py", line 119, in handle_error_response
Feb 21 15:04:54 api-vm-default gunicorn[26814]:     raise err
Feb 21 15:04:54 api-vm-default gunicorn[26814]: stripe.error.APIError: Request req_vSnTuIEKcoRIRn: There is currently another in-progress request using this Idempotent Key (that probably means you submitted twice, and the other request is still going through): 2YAY37src_1E6J6RJW4tzPOZOnAQbMvq6n. Please try again later.
Feb 21 15:04:54 api-vm-default gunicorn[26814]: During handling of the above exception, another exception occurred:
Feb 21 15:04:54 api-vm-default gunicorn[26814]: Traceback (most recent call last):
Feb 21 15:04:54 api-vm-default gunicorn[26814]:   File "/var/pretix/venv/lib/python3.5/site-packages/pretix/plugins/stripe/views.py", line 338, in source_webhook
Feb 21 15:04:54 api-vm-default gunicorn[26814]:     prov._charge_source(None, source_id, payment)
Feb 21 15:04:54 api-vm-default gunicorn[26814]:   File "/var/pretix/venv/lib/python3.5/site-packages/pretix/plugins/stripe/payment.py", line 354, in _charge_source
Feb 21 15:04:54 api-vm-default gunicorn[26814]:     raise PaymentException(_('We had trouble communicating with Stripe. Please try again and get in touch '
Feb 21 15:04:54 api-vm-default gunicorn[26814]: pretix.base.payment.PaymentException: We hadden problemen met het communiceren met Stripe. Probeer het opnieuw, en neem contact op met ons als het probleem aanhoudt.
Feb 21 15:04:54 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:54,931 stripe util message='Stripe API response' path=https://api.stripe.com/v1/charges response_code=200
Feb 21 15:04:55 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:55,641 stripe util message='Request to Stripe api' method=get path=https://api.stripe.com/v1/charges/py_1E6J6YJW4tzPOZOn4Bo3WFcS?expand%5B%5D=dispute
Feb 21 15:04:56 api-vm-default gunicorn[26814]: INFO 2019-02-21 16:04:56,422 stripe util message='Stripe API response' path=https://api.stripe.com/v1/charges/py_1E6J6YJW4tzPOZOn4Bo3WFcS?expand%5B%5D=dispute response_code=200
```

**Comment by raphaelm** [comment]
These things are complicated, depend on the payment method (and even on the card type, whether 3DS is enabled, …) and there are one or two redirects in between, but to simplify, this is what happens:

1. After the order is confirmed, we create a payment *source* with Stripe.
2. Then, we poll to check if the source is *chargeable*.
3. If it is, we create a *charge*, which actually moves the money.
4. Then, we poll to check if the charge was *successful* and mark the order as paid.

Stripe, however, also sends a webhook after step 1 and step 3. If we receive the webhook event "source chargeable", we also create a charge and check for it's status.

If the first webhook and our polling in step 2 happen *at the same time*, we get a race condition. Since we supply the same *idenpotency key* to Stripe in both requests, Stripe detects the race condition and the worst thing that happens is this logged error.

We can't get rid of the race condition on our side since,

* we can't stop listening for webhooks, since a person might no longer be there after step 1, e.g. because their browser crashed, internet was interrupted, or it just took to long and they abandoned the site
* we can't stop polling, since there's no guarantee the admin configured webhooks correctly or that Stripe is delivering them fast enough. If they're not delivered fast enough, not polling would make for a bad user experience

I guess the only thing we *could* do is detect that exact error message and silence it.

**Comment by Zambiorix** [comment]
:-) no worries!
I only report because I couldn't find anything in the github issue history and I always think: is it only on my system due to configuration or not ...

Thanks!
