### ISSUE TITLE
Login is not working after updating to 2.5.0

### ISSUE THREAD

**Issue by ZEROF** [pretix/pretix#1229]
HI,

After upgrading to 2.5 I can't login any more, I get this error:

    Verification failed
    We could not verify that this request really was sent from you. For security reasons, we      therefore cannot process it.
    Please go back to the last page, refresh this page and then try again. If the problem persists, please get in touch with us.
    Take a step back 
    I got back to loging page, I try again, and I get same error, over and over.

**This is update output:**

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/pretix/src/pretix/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 85, in handle
    executor.loader.check_consistent_history(connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 297, in check_consistent_history
    connection.alias,
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration pretixbase.0089_auto_20180315_1322 is applied before its dependency pretixapi.0001_initial on database 'default'.

Full output can be found here from docker logs (docker logs -f):

https://paste.lugons.org/?1fa5a1f35726c15e#y7ljyeYpRWssgOilncotLNeYbqRzvu8+F4pSpMhl3HE=

**Comment by raphaelm** [comment]
Those appear to be two independent problems. To be hones, I have no idea how the migrations order got screwed up – can you post the content of the django_migrations database table?

For the error during login – can you check if something turns up in pretix.log?

**Comment by ZEROF** [comment]
Hi,

This is dump of table:

https://paste.lugons.org/?f829e845c6ff2fba#KMJKCHn4HHl3k6cKMyX6I0Yd9tBTREEgY3BJcAMCfhY=

This is error I get when i try to login(this is from pretix.log):

https://paste.lugons.org/?9358d63906188604#h+8aR5YQ7QEaa1mtJ2a056fBFAcK51NgfjjU14wthPc=

For info, everything working fine with old docker image (i made backup before updating).

**Comment by raphaelm** [comment]
closing for inactivity
