### ISSUE TITLE
Problems editing events

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#128]
> - Editing a newly created event is not possible:
>     The name-field is not-editable and empty although an event name was given during creation
>     On submission, the submitted change is rejected with "This field is required" for name
> 
>   Database looks like this:
> 
```
    >>> from pretix.base.models.event import Event
    >>> event = Event.objects.all()[0]
    >>> event.name
    <LazyI18nString: {'de': 'CryptoCon16', 'en': 'CryptoCon16', 'de-informal': 'CryptoCon16'}>
    >>> repr(event)
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/var/pretix/env/lib/python3.4/site-packages/django/db/models/base.py", line 459, in __repr__
        u = six.text_type(self)
      File "/var/pretix/src/src/pretix/base/models/event.py", line 104, in __str__
        return str(self.name)
      File "/var/pretix/src/src/pretix/base/i18n.py", line 44, in __str__
        firstpart = lng.split('-')[0]
    AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by cfra** [comment]
This turned out to be PEBCAK.
I had configured an invalid locale in /etc/pretix/pretix.cfg (de_Informal instead of de-informal). This incorrect locale ended up in the locale setting of the event object, causing the lookup in event.name to fail.

**Comment by raphaelm** [comment]
Okay, then let's change the scope of this issue ;)
