### ISSUE TITLE
[2.8.2] Database Error while accesing quotas in backend

### ISSUE THREAD

**Issue by MaxRink** [pretix/pretix#1320]
This is the Error Message from the Log when i try to access the quota page in the backend.
`ERROR 2019-06-13 11:47:11,676 django.request log Internal Server Error: /control/event/frrm/cpu19/quotas/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pretix.pretixbase_quota_items.quota_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")

The above exception was the direct cause of the following exception:

.... more stuff...

django.db.utils.OperationalError: (1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pretix.pretixbase_quota_items.quota_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")

`
The Setup is the official Docker Container 
All Migrations have run and i cant spot anything wron in my Setup

**Comment by raphaelm** [comment]
Please see this issue: https://github.com/pretix/pretix/issues/591#issuecomment-320780618
