### ISSUE TITLE
Cron error after update to 2.8.2 - missing "pretixbase_order.email_known_to_work"

### ISSUE THREAD

**Issue by bpcurse** [pretix/pretix#1323]
After update from 2.6.0 to 2.8.2 cron job reports the following error:

```
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/var/pretix/venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/var/pretix/venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/var/pretix/venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'pretixbase_order.email_known_to_work' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/base/management/commands/runperiodic.py", line 11, in handle
    periodic_task.send(self)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/base/services/orders.py", line 811, in expire_orders
    require_approval=False).select_related('event'):
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/var/pretix/venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/var/pretix/venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/var/pretix/venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'pretixbase_order.email_known_to_work' in 'field list'")
```
Using MariaDB 10.3.13, the primitive approach to create an empty column named "email_known_to_work" in table "pretixbase_order" with the same properties as "email" does not help.

**Comment by pc-coholic** [comment]
Random question: Did you run the `migrate`-command after the update?

**Comment by bpcurse** [comment]
@pc-coholic Thank you for your reply.
Yes, I did the following (previous updates had succeeded this way):

as pretix user:
source /var/pretix/venv/bin/activate
(venv)$ pip3 install -U pretix[mysql] gunicorn
(venv)$ python -m pretix migrate
(venv)$ python -m pretix rebuild
(venv)$ python -m pretix updatestyles

as root:
systemctl restart pretix-web pretix-worker

**Comment by bpcurse** [comment]
> Using MariaDB 10.3.13, the primitive approach to create an empty column named "email_known_to_work" in table "pretixbase_order" with the same properties as "email" does not help.

To be more precise it does help a little to get to the next error:
```
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/var/pretix/venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/var/pretix/venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/var/pretix/venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'pretix2.pretixapi_apicall' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/base/management/commands/runperiodic.py", line 11, in handle
    periodic_task.send(self)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/api/signals.py", line 26, in cleanup_api_logs
    ApiCall.objects.filter(created__lte=now() - timedelta(hours=24)).delete()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/models/query.py", line 711, in delete
    deleted, _rows_count = collector.delete()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/models/deletion.py", line 294, in delete
    count = qs._raw_delete(using=self.using)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/models/query.py", line 725, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 75, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/var/pretix/venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/var/pretix/venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/var/pretix/venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'pretix2.pretixapi_apicall' doesn't exist")
```

I have run python -m pretix migrate (in the venv) again to be absolutely sure. It outputs the following:
```
Operations to perform:
  Apply all migrations: auth, badges, banktransfer, contenttypes, oauth2_provider, otp_static, otp_totp, paypal, pretixapi, pretixbase, pretixdroid, pretixhelpers, pretixmultidomain, sessions, stripe, ticketoutputpdf
Running migrations:
  No migrations to apply.
```

**Comment by raphaelm** [comment]
Yeah, somehow the migrations didn't run correctly, or the respective tables and columns would have been created. Please:

* Remove the column you manually created to prevent further problems.
* Post the contents of the ``django_migrations`` table in your database
* Post the output of ``python -m pretix showmigrations``

**Comment by bpcurse** [comment]
Thank you for your help! It's not a direct pretix issue and has been solved in the meantime.

Due to the missing compatibility with python 3.7 in older celery versions, python 3.6 and python 3.7 had to be installed on the server in parallel.

When issuing the migration command I simply forgot to explicitly specify python 3.6:
`python3.6 -m pretix migrate` instead of `python -m pretix migrate` did the job on manjaro/arch linux
