### ISSUE TITLE
django.db.utils.IntegrityError: NOT NULL constraint failed: new__pretixdroid_appconfiguration.list_i

### ISSUE THREAD

**Issue by ligi** [pretix/pretix#1340]
wanted to setup the dev environment on the latest HEAD (be310a4e4763b006ff632f80635b749f0ff4df0e) - but I am getting this error:

```
(env) ligi@lip1:~/git/3rd/pretix/src$ python manage.py migrate
Operations to perform:
  Apply all migrations: auth, badges, banktransfer, contenttypes, oauth2_provider, otp_static, otp_totp, paypal, pretixapi, pretixbase, pretixdroid, pretixhelpers, pretixmultidomain, sessions, stripe, ticketoutputpdf
Running migrations:
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying pretixdroid.0002_auto_20161208_1644... OK
  Applying pretixbase.0047_auto_20161126_1300... OK
  Applying pretixbase.0048_auto_20161129_1330... OK
  Applying pretixbase.0049_checkin... OK
  Applying pretixbase.0050_orderposition_positionid_squashed_0061_event_location... OK
  Applying pretixbase.0051_auto_20170206_2027_squashed_0057_auto_20170501_2116... OK
  Applying pretixbase.0052_team_teaminvite_squashed_0070_auto_20170719_0910... OK
  Applying pretixbase.0071_auto_20170729_1616_squashed_0075_auto_20170828_0901... OK
  Applying pretixbase.0076_orderfee_squashed_0082_invoiceaddress_internal_reference... OK
  Applying pretixbase.0077_auto_20171124_1629_squashed_0088_auto_20180328_1217... OK
  Applying badges.0001_initial... OK
  Applying badges.0002_auto_20190201_1424... OK
  Applying banktransfer.0004_auto_20170619_1125... OK
  Applying banktransfer.0005_auto_20181023_2209... OK
  Applying oauth2_provider.0001_initial... OK
  Applying oauth2_provider.0002_08_updates... OK
  Applying oauth2_provider.0003_auto_20160316_1503... OK
  Applying oauth2_provider.0004_auto_20160525_1623... OK
  Applying oauth2_provider.0005_auto_20170514_1141... OK
  Applying oauth2_provider.0006_auto_20171214_2232... OK
  Applying pretixapi.0001_initial... OK
  Applying pretixbase.0089_auto_20180315_1322... OK
  Applying pretixbase.0090_auto_20180509_0917_squashed_0095_auto_20180604_1129... OK
  Applying pretixbase.0096_auto_20180722_0801... OK
  Applying pretixbase.0097_auto_20180722_0804... OK
  Applying paypal.0001_initial... OK
  Applying paypal.0002_referencedpaypalobject_payment... OK
  Applying pretixbase.0098_auto_20180731_1243_squashed_0100_item_require_approval... OK
  Applying pretixbase.0099_auto_20180912_1035... OK
  Applying pretixbase.0100_auto_20181023_2300... OK
  Applying pretixbase.0101_auto_20181025_2255... OK
  Applying pretixbase.0102_auto_20181017_0024... OK
  Applying pretixbase.0103_auto_20181121_1224... OK
  Applying pretixbase.0104_auto_20181114_1526... OK
  Applying pretixbase.0105_auto_20190112_1512_squashed_0107_auto_20190129_1337... OK
  Applying pretixbase.0108_auto_20190201_1527... OK
  Applying pretixbase.0109_auto_20190208_1432... OK
  Applying pretixbase.0110_auto_20190219_1245... OK
  Applying pretixbase.0111_auto_20190219_0949... OK
  Applying pretixbase.0112_auto_20190304_1726... OK
  Applying pretixbase.0113_auto_20190312_0942... OK
  Applying pretixbase.0114_auto_20190316_1014... OK
  Applying pretixbase.0115_auto_20190323_2238... OK
  Applying pretixbase.0116_auto_20190402_0722... OK
  Applying pretixapi.0002_auto_20180604_1120... OK
  Applying pretixapi.0003_webhook_webhookcall_webhookeventlistener... OK
  Applying pretixapi.0004_auto_20190405_1048... OK
  Applying pretixbase.0117_auto_20190418_1149... OK
  Applying pretixbase.0118_auto_20190423_0839... OK
  Applying pretixbase.0119_auto_20190509_0654... OK
  Applying pretixbase.0120_auto_20190509_0736... OK
  Applying pretixbase.0121_order_email_known_to_work... OK
  Applying pretixbase.0122_orderposition_web_secret... OK
  Applying pretixbase.0123_auto_20190530_1035... OK
  Applying pretixbase.0124_seat_seat_guid... OK
  Applying pretixbase.0125_voucher_show_hidden_items... OK
  Applying pretixbase.0126_item_show_quota_left... OK
  Applying pretixbase.0127_auto_20190711_0705... OK
  Applying pretixdroid.0003_appconfiguration_squashed_0005_auto_20180106_2122...Traceback (most recent call last):
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: new__pretixdroid_appconfiguration.list_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 137, in alter_field
    super().alter_field(model, old_field, new_field, strict=strict)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 535, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 359, in _alter_field
    self._remake_table(model, alter_field=(old_field, new_field))
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 286, in _remake_table
    self.quote_name(model._meta.db_table),
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: new__pretixdroid_appconfiguration.list_id

```

**Comment by ligi** [comment]
hm - worked after a clean checkout - must have been some residue from previous versions - feel free to close (just keeping it open in case you see a thing to fix in there)

**Comment by raphaelm** [comment]
Hmm, no, probably some unclean dev environment. Glad it works now!

**Comment by ligi** [comment]
thanks - but it fails in the next step:

```
(env) ligi@lip1:~/git/3rd/pretix/src$ python make_testdata.py
/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1421: RuntimeWarning: DateTimeField Event.date_from received a naive datetime (2020-09-04 17:00:00) while time zone support is active.
  RuntimeWarning)
/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1421: RuntimeWarning: DateTimeField Event.date_to received a naive datetime (2020-09-06 17:00:00) while time zone support is active.
  RuntimeWarning)
Traceback (most recent call last):
  File "make_testdata.py", line 48, in <module>
    type=Question.TYPE_NUMBER, required=False
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ligi/git/3rd/pretix/src/pretix/base/models/items.py", line 1052, in save
    if not Question.objects.filter(event=self.event, identifier=code).exists():
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ligi/git/3rd/pretix/env/lib/python3.6/site-packages/django_scopes/manager.py", line 15, in error
    ', '.join(self.missing_scopes)
django_scopes.exceptions.ScopeError: A scope on dimension(s) organizer needs to be active for this query.

```

**Comment by raphaelm** [comment]
Oops, ``make_testdata.py`` doesn't work any more, we need to see if we fix it or remove it from the docs… Thanks for noticing. You don't need it, you can just use admin@localhost and admin to log in and create an event on your own

**Comment by naveens800** [comment]
how can you fixed this plz help!!!!!!!!

**Comment by Akanmu01** [comment]
please help me to fix this  "NOT NULL constraint failed: blog_app_comment.post_id"

**Comment by raphaelm** [comment]
@Akanmu01 there is no blog_app_comment in pretix
