### ISSUE TITLE
Log entries too verbose when shops are unavailable

### ISSUE THREAD

**Issue by bpcurse** [pretix/pretix#1420]
If a shop is deactivated, every user's attempt to access it, seems to result in 11 lines in the log by gunicorn. Many access attempts lead to an unnecessarily large log file.

Is there a way to reduce this to 1 or 2 lines?

Sample log:
```
Sep 25 10:31:59 xxxxx gunicorn[7945]: WARNING 2019-09-25 08:31:59,370 django.request log Forbidden (Permission denied): /xxxxx/xxxxx/
Sep 25 10:31:59 xxxxx gunicorn[7945]: Traceback (most recent call last):
Sep 25 10:31:59 xxxxx gunicorn[7945]:   File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
Sep 25 10:31:59 xxxxx gunicorn[7945]:     response = get_response(request)
Sep 25 10:31:59 xxxxx gunicorn[7945]:   File "/var/pretix/venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
Sep 25 10:31:59 xxxxx gunicorn[7945]:     response = self.process_request(request)
Sep 25 10:31:59 xxxxx gunicorn[7945]:   File "/var/pretix/venv/lib/python3.6/site-packages/pretix/presale/middleware.py", line 17, in process_request
Sep 25 10:31:59 xxxxx gunicorn[7945]:     redirect = _detect_event(request, require_live=url.url_name != 'event.widget.productlist')
Sep 25 10:31:59 xxxxx gunicorn[7945]:   File "/var/pretix/venv/lib/python3.6/site-packages/pretix/presale/utils.py", line 94, in _detect_event
Sep 25 10:31:59 xxxxx gunicorn[7945]:     raise PermissionDenied(_('The selected ticket shop is currently not available.'))
Sep 25 10:31:59 xxxxx gunicorn[7945]: django.core.exceptions.PermissionDenied: Der ausgewählte Ticket-Shop ist im Moment nicht verfügbar.
```

**Comment by raphaelm** [comment]
Hmm, I'm not sure if there's a good way to change the logging behaviour of that specific exception. I agree that we do not need a traceback here, though.
