### ISSUE TITLE
Internal Server Error when trying to view reseller-Page in the front-end

### ISSUE THREAD

**Issue by flibMS** [pretix/pretix#1531]
After Upgrade to pretix  3.4.0 and resellers-plugin 1.5.0 - we get the following error (internal server error) when i click the reseller-page:

pretix.log -->
ERROR 2019-12-19 15:54:07,141 django.request log Internal Server Error: /reseller/
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 131, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/var/pretix/venv/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 90, in render_compressed
    return self.render_offline(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 64, in render_offline
    original_content = self.get_original_content(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 123, in get_original_content
    return self.nodelist.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/templatetags/static.py", line 106, in render
    url = self.url(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/templatetags/static.py", line 103, in url
    return self.handle_simple(path)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 153, in url
    return self._url(self.stored_name, name, force)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 132, in _url
    hashed_name = hashed_name_func(*args)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 420, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'pretix_resellers/scss/resellers.scss'

**Comment by raphaelm** [comment]
For issues with pretix Enterprise plugins please reach out to support@pretix.eu. Thanks! :)
