### ISSUE TITLE
Internal Server Error when trying to view page-plugin settings in the event page

### ISSUE THREAD

**Issue by flibMS** [pretix/pretix#1532]
When i click the pages-settings in the event page, i am getting Internal Server Error (since pages-plugin installation).

pretix.log -->
ERROR 2019-12-19 16:06:02,868 django.request log Internal Server Error: /control/event/test/test/pages/
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/control/context.py", line 43, in contextprocessor
    for receiver, response in html_head.send(request.event, request=request):
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/base/signals.py", line 70, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/pretix/src/pretix-pages/pretix_pages/signals.py", line 95, in html_head_control
    return template.render({})
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 131, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/var/pretix/venv/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 90, in render_compressed
    return self.render_offline(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 64, in render_offline
    original_content = self.get_original_content(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 123, in get_original_content
    return self.nodelist.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/templatetags/static.py", line 106, in render
    url = self.url(context)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/templatetags/static.py", line 103, in url
    return self.handle_simple(path)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 153, in url
    return self._url(self.stored_name, name, force)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 132, in _url
    hashed_name = hashed_name_func(*args)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 420, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'pretix_pages/quill/quill.snow.css'

**Comment by flibMS** [comment]
Incorrect permissions under /var/pretix/venv caused the problem. "chown -R pretix" and a rebuild fixed the problem.
