### ISSUE TITLE
error massage ImportError: cannot import name 'pub_key_from_der' from 'u2flib_server.utils'

### ISSUE THREAD

**Issue by sul6anheart** [pretix/pretix#1553]
Hello, everyone, I cant  collect static this is the massage
` File "/Users/mumirahibrahim/Desktop/pretix/src/pretix/base/models/__init__.py", line 2, in <module>
ImportError: cannot import name 'pub_key_from_der' from 'u2flib_server.utils' (/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/u2flib_server/utils.py)`
and these
` from .auth import U2FDevice, User, WebAuthnDevice
  File "/Users/mumirahibrahim/Desktop/pretix/src/pretix/base/models/auth.py", line 20, in <module>
`

**Comment by raphaelm** [comment]
Can you please paste the full error message as well as the output of ``pip freeze``?

**Comment by sul6anheart** [comment]
amqp==2.5.2
appnope==0.1.0
asgiref==3.2.3
asn1crypto==0.24.0
Babel==2.8.0
backcall==0.1.0
billiard==3.6.1.0
cached-property==1.5.1
cairocffi==1.1.0
CairoSVG==2.4.2
cbor2==4.2.0
celery==4.4.0
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
conda==4.7.10
conda-package-handling==1.3.11
consoleLog==0.2.4
coverage==3.7.1
coveralls==0.5
cryptography==2.7
cssselect==1.1.0
cssselect2==0.2.2
decorator==4.4.0
defusedxml==0.6.0
dj-database-url==0.4.2
Django==3.0.2
django-activatable-model==1.2.1
django-appconf==1.0.3
django-autoslug==1.9.6
django-bootstrap3==11.1.0
django-braces==1.9.0
django-cities-light==3.4.0
django-classy-tags==0.9.0
django-cms==3.7.0
django-compat==1.0.15
django-compressor==2.4
django-countries==5.5
django-crispy-forms==1.7.0
django-dotenv==1.4.2
django-easy-pdf==0.1.1
django-entity==4.2.0
django-entity-event==1.2.0
django-environ==0.4.5
django-filer==1.6.0
django-filter==2.2.0
django-filters==0.2.1
django-formset-js==0.5.0
django-formtools==2.1
django-hierarchy==0.2.3
django-hierarkey==1.0.3
django-hijack==2.1.10
django-i18nfield==1.6.1
django-jquery-js==3.1.1
django-js-asset==1.2.2
django-manager-utils==1.4.0
django-markup==1.4.1
django-mptt==0.10.0
django-nose==1.4.6
django-oauth-toolkit==1.2.0
django-otp==0.7.5
django-phonenumber-field==4.0.0
django-polymorphic==2.0.3
django-query-builder==1.2.0
django-scopes==1.2.0
django-sekizai==1.0.0
django-statici18n==1.9.0
django-treebeard==4.3
djangocms-admin-style==1.4.0
djangocms-attributes-field==1.1.0
djangocms-bootstrap4==1.5.0
djangocms-file==2.3.0
djangocms-googlemap==1.3.0
djangocms-icon==1.4.2
djangocms-installer==1.2.0
djangocms-link==2.5.0
djangocms-picture==2.3.0
djangocms-snippet==2.2.0
djangocms-style==2.2.0
djangocms-text-ckeditor==3.8.0
djangocms-video==2.2.0
djangorestframework==3.7.3
docopt==0.6.2
easy-thumbnails==2.6
flake8==3.4.1
fleming==0.5.0
future==0.18.2
gunicorn==19.7.1
html5lib==1.0.1
idna==2.8
importlib-metadata==1.4.0
ipython==7.7.0
ipython-genutils==0.2.0
jedi==0.15.1
Jinja2==2.10
jsonfield==2.0.2
kombu==4.6.7
libarchive-c==2.8
lxml==4.4.2
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==8.1.0
mysqlclient==1.4.5
nose==1.3.7
oauthlib==3.0.1
parso==0.5.1
pexpect==4.7.0
phonenumbers==8.8.8
pickleshare==0.7.5
Pillow==5.1.0
progressbar2==3.47.0
prompt-toolkit==2.0.9
psycopg2==2.7.4
psycopg2-binary==2.7.4
ptyprocess==0.6.0
pycodestyle==2.3.1
pycosat==0.6.3
pycountry==19.8.18
pycparser==2.19
pyflakes==1.5.0
Pygments==2.4.2
PyJWT==1.7.1
PyMySQL==0.9.3
pyOpenSSL==19.0.0
PyPDF2==1.26.0
Pyphen==0.9.5
PySocks==1.7.0
python-dateutil==2.8.0
python-u2flib-server==5.0.0
python-utils==2.3.0
python3-openid==3.1.0
python3-utils==0.4.0
pytz==2019.1
PyYAML==3.11
rcssmin==1.0.6
reportlab==3.5.32
requests==2.22.0
requests-oauthlib==1.2.0
rjsmin==1.1.0
ruamel-yaml==0.15.46
selenium==3.4.0
six==1.12.0
social-auth-app-django==3.1.0
social-auth-core==3.2.0
sqlparse==0.3.0
tinycss==0.4
tinycss2==1.0.2
tqdm==4.32.1
traitlets==4.3.2
tzlocal==2.0.0
Unidecode==0.4.19
urllib3==1.25.3
vine==1.3.0
wcwidth==0.1.7
WeasyPrint==0.34
webauthn==0.4.5
webencodings==0.5.1
whitenoise==3.3.1
wrapt==1.11.2
xhtml2pdf==0.2.3
zipp==2.0.0

**Comment by sul6anheart** [comment]
`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/mumirahibrahim/Desktop/pretix/src/pretix/base/models/__init__.py", line 2, in <module>
    from .auth import U2FDevice, User, WebAuthnDevice
  File "/Users/mumirahibrahim/Desktop/pretix/src/pretix/base/models/auth.py", line 20, in <module>
    from u2flib_server.utils import (
ImportError: cannot import name 'pub_key_from_der' from 'u2flib_server.utils' (/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/u2flib_server/utils.py)`

**Comment by raphaelm** [comment]
You have python-u2flib-server==5.0.0 installed, pretix depends on the 4.x version.

**Comment by sul6anheart** [comment]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/mumirahibrahim/Desktop/pretix/src/pretix/base/models/__init__.py", line 4, in <module>
    from .checkin import Checkin, CheckinList
  File "/Users/mumirahibrahim/Desktop/pretix/src/pretix/base/models/checkin.py", line 8, in <module>
    from pretix.base.models.fields import MultiStringField
  File "/Users/mumirahibrahim/Desktop/pretix/src/pretix/base/models/fields.py", line 4, in <module>
    from rest_framework import serializers
  File "/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/rest_framework/serializers.py", line 26, in <module>
    from django.utils import six, timezone
ImportError: cannot import name 'six' from 'django.utils' (/Users/mumirahibrahim/miniconda3/lib/python3.7/site-packages/django/utils/__init__.py)
