### ISSUE TITLE
MySQLdb._exceptions.OperationalError: (1050, "Table 'pretixbase_itembundle' already exists")

### ISSUE THREAD

**Issue by omercnet** [pretix/pretix#1583]
upgrading from 2.5 to 2.6 I get this error during migration

```  Applying pretixbase.0114_auto_20190316_1014...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1050, "Table 'pretixbase_itembundle' already exists")
```

ideas?

**Comment by omercnet** [comment]
ended up being a db issue, unrelated to pretix
