### ISSUE TITLE
django_mysql dependency must be raised

### ISSUE THREAD

**Issue by DerDakon** [pretix/pretix#1654]
I had django_mysql-2.4.1 installed in pip, and it was not upgraded during update to 3.8.0. However I got the following errors afterwards:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pretix/.local/lib/python3.6/site-packages/pretix/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pretix/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/pretix/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/pretix/.local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pretix/.local/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/pretix/.local/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frothzen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pretix/.local/lib/python3.6/site-packages/pretix/base/models/__init__.py", line 19, in <module>
    from .orders import (
  File "/home/pretix/.local/lib/python3.6/site-packages/pretix/base/models/orders.py", line 33, in <module>
    from jsonfallback.fields import FallbackJSONField
  File "/home/pretix/.local/lib/python3.6/site-packages/jsonfallback/fields.py", line 10, in <module>
    from django_mysql.checks import mysql_connections
  File "/home/pretix/.local/lib/python3.6/site-packages/django_mysql/checks.py", line 9, in <module>
    from django_mysql.utils import collapse_spaces
  File "/home/pretix/.local/lib/python3.6/site-packages/django_mysql/utils.py", line 17, in <module>
    from django.utils import six
```

After wiping django_mysql and running the upgrade again a newer version (3.x) got installed and the error went away.

**Comment by raphaelm** [comment]
Thanks for reporting. pretix does not directly depend on django_mysql, but https://github.com/raphaelm/django-jsonfallback does, so we should increase it there.
