### ISSUE TITLE
ModuleNotFoundError: No module named 'production_settings'

### ISSUE THREAD

**Issue by lamatastisch** [pretix/pretix#1741]
I got the following error while I tried to use the docker-compose file of [this](https://github.com/codydjango/pretix-docker-compose) repository.
```
pretix      | Traceback (most recent call last):
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
pretix      |     self.execute(*args, **cmd_options)
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 366, in execute
pretix      |     self.check()
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 395, in check
pretix      |     include_deployment_checks=include_deployment_checks,
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 63, in _run_checks
pretix      |     issues = run_checks(tags=[Tags.database])
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
pretix      |     new_errors = check(app_configs=app_configs)
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/database.py", line 9, in check_database_backends
pretix      |     for conn in connections.all():
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 222, in all
pretix      |     return [self[alias] for alias in self]
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 219, in __iter__
pretix      |     return iter(self.databases)
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
pretix      |     res = instance.__dict__[self.name] = self.func(instance)
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 153, in databases
pretix      |     self._databases = settings.DATABASES
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 76, in __getattr__
pretix      |     self._setup(name)
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 63, in _setup
pretix      |     self._wrapped = Settings(settings_module)
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 142, in __init__
pretix      |     mod = importlib.import_module(self.SETTINGS_MODULE)
pretix      |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
pretix      |     return _bootstrap._gcd_import(name[level:], package, level)
pretix      |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
pretix      |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
pretix      |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
pretix      | ModuleNotFoundError: No module named 'production_settings'
pretix      |
pretix      | During handling of the above exception, another exception occurred:
pretix      |
pretix      | Traceback (most recent call last):
pretix      |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
pretix      |     "__main__", mod_spec)
pretix      |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
pretix      |     exec(code, run_globals)
pretix      |   File "/usr/local/lib/python3.6/site-packages/pretix/__main__.py", line 9, in <module>
pretix      |     execute_from_command_line(sys.argv)
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
pretix      |     utility.execute()
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
pretix      |     self.fetch_command(subcommand).run_from_argv(self.argv)
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 341, in run_from_argv
pretix      |     connections.close_all()
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 225, in close_all
pretix      |     for alias in self:
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 219, in __iter__
pretix      |     return iter(self.databases)
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
pretix      |     res = instance.__dict__[self.name] = self.func(instance)
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 153, in databases
pretix      |     self._databases = settings.DATABASES
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 76, in __getattr__
pretix      |     self._setup(name)
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 63, in _setup
pretix      |     self._wrapped = Settings(settings_module)
pretix      |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 142, in __init__
pretix      |     mod = importlib.import_module(self.SETTINGS_MODULE)
pretix      |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
pretix      |     return _bootstrap._gcd_import(name[level:], package, level)
pretix      |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
pretix      |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
pretix      |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
pretix      | ModuleNotFoundError: No module named 'production_settings'

```
Please help! Thank you in advance.

**Comment by raphaelm** [comment]
Please open an issue with that repository then. docker-compose is not one of the officially supported ways to run pretix.
