### ISSUE TITLE
AmbiguousTimeError for automatic checkout

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#1832]
While standard pretix datetime fields can handle ambiguous times when switching from daylight savings (like only today this year)

![image](https://user-images.githubusercontent.com/5970076/97112694-0cebc800-16e6-11eb-9c72-06f8f1f76bff.png)

the time set on checkin lists to automatically check out participants introduced in #1819 can generate a `pytz.AmbiguousTimeError`.
![image](https://user-images.githubusercontent.com/5970076/97112774-72d84f80-16e6-11eb-8989-a97c6a6dd6d1.png)

```python
Traceback (most recent call last):
  File "/home/felix/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/felix/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/felix/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/felix/tickets/pretix/src/pretix/control/permissions.py", line 28, in wrapper
    return function(request, *args, **kw)
  File "/home/felix/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/felix/tickets/pretix/src/pretix/control/views/checkin.py", line 272, in dispatch
    r = super().dispatch(request, *args, **kwargs)
  File "/home/felix/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/felix/.local/lib/python3.6/site-packages/django/views/generic/edit.py", line 194, in post
    return super().post(request, *args, **kwargs)
  File "/home/felix/.local/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/home/felix/.local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in is_valid
    return self.is_bound and not self.errors
  File "/home/felix/.local/lib/python3.6/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/home/felix/.local/lib/python3.6/site-packages/django/forms/forms.py", line 376, in full_clean
    self._clean_fields()
  File "/home/felix/.local/lib/python3.6/site-packages/django/forms/forms.py", line 394, in _clean_fields
    value = field.clean(value)
  File "/home/felix/.local/lib/python3.6/site-packages/django/forms/fields.py", line 148, in clean
    value = self.to_python(value)
  File "/home/felix/tickets/pretix/src/pretix/control/forms/checkin.py", line 25, in to_python
    ), tz)
  File "/home/felix/.local/lib/python3.6/site-packages/django/utils/timezone.py", line 270, in make_aware
    return timezone.localize(value, is_dst=is_dst)
  File "/home/felix/.local/lib/python3.6/site-packages/pytz/tzinfo.py", line 363, in localize
    raise AmbiguousTimeError(dt)
pytz.exceptions.AmbiguousTimeError: 2020-10-25 02:00:00
```

<small>I'm sorry.</small>

**Comment by felixrindt** [comment]
Also, when writing `03:30:00` in the form it gets saved and then displayed as `02:30:00`, which in turn can't be saved again.

**Comment by felixrindt** [comment]
There has been some DST-related changes to automatic checkout processing (https://github.com/pretix/pretix/commit/552d13ef6cf568ffc3702cbeb20ab5af7497bc4b), but from what I gather by reading the code, it did not fix this issue, which is related  to the form.

**Comment by raphaelm** [comment]
Note to self: Re-check this after #2989 is done

**Comment by raphaelm** [comment]
No longer an issue. See also 552d13ef. I added an regression test.
