### ISSUE TITLE
UnknownLocaleError on updatestyles after update to 3.14.0

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#1888]
I just performed the update as suggested on Twitter, the `python -m pretix updatestyles` step fails with the following trace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/pretix/venv/lib/python3.8/site-packages/pretix/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/var/pretix/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/var/pretix/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/pretix/venv/lib/python3.8/site-packages/pretix/multidomain/maindomain_urlconf.py", line 11, in <module>
    from pretix.urls import common_patterns
  File "/var/pretix/venv/lib/python3.8/site-packages/pretix/urls.py", line 5, in <module>
    import pretix.control.urls
  File "/var/pretix/venv/lib/python3.8/site-packages/pretix/control/urls.py", line 3, in <module>
    from pretix.control.views import (
  File "/var/pretix/venv/lib/python3.8/site-packages/pretix/control/views/orders.py", line 80, in <module>
    from pretix.control.forms.orders import (
  File "/var/pretix/venv/lib/python3.8/site-packages/pretix/control/forms/orders.py", line 455, in <module>
    class OrderContactForm(forms.ModelForm):
  File "/var/pretix/venv/lib/python3.8/site-packages/pretix/control/forms/orders.py", line 462, in OrderContactForm
    class Meta:
  File "/var/pretix/venv/lib/python3.8/site-packages/pretix/control/forms/orders.py", line 466, in Meta
    'phone': WrappedPhoneNumberPrefixWidget()
  File "/var/pretix/venv/lib/python3.8/site-packages/phonenumber_field/widgets.py", line 46, in __init__
    widgets = (PhonePrefixSelect(initial), TextInput())
  File "/var/pretix/venv/lib/python3.8/site-packages/phonenumber_field/widgets.py", line 23, in __init__
    locale = Locale(translation.to_locale(language))
  File "/var/pretix/venv/lib/python3.8/site-packages/babel/core.py", line 168, in __init__
    raise UnknownLocaleError(identifier)
babel.core.UnknownLocaleError: unknown locale 'de_Informal'
```

**Comment by raphaelm** [comment]
Bug confirmed, happens when

```
[locale]
default=de_Informal
```

is set in pretix.cfg

**Comment by raphaelm** [comment]
3.14.1 on PyPI soon

**Comment by thegcat** [comment]
Vielen Dank!
