### ISSUE TITLE
ImportError on cryptography.hazmat with pretix migrate in secrets.py

### ISSUE THREAD

**Issue by Danukeru** [pretix/pretix#1975]
Using:
- Debian testing
- new python 3.9 virtualenv 
- postgresql
- pretix 3.15.0 
- cryptography 3.4.6
- [Following manual smallscale deployment](https://docs.pretix.eu/en/latest/admin/installation/manual_smallscale.html)
```
(test) root@pet:/opt/pretix# python -m pretix migrate
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/pretix/test/lib/python3.9/site-packages/pretix/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/pretix/test/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/pretix/test/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/pretix/test/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/pretix/test/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/pretix/test/lib/python3.9/site-packages/pretix/base/__init__.py", line 15, in ready
    from .services import auth, checkin, export, mail, tickets, cart, orderimport, orders, invoices, cleanup, update_check, quotas, notifications, vouchers  # NOQA
  File "/opt/pretix/test/lib/python3.9/site-packages/pretix/base/services/orders.py", line 43, in <module>
    from pretix.base.secrets import assign_ticket_secret
  File "/opt/pretix/test/lib/python3.9/site-packages/pretix/base/secrets.py", line 7, in <module>
    from cryptography.hazmat.primitives.serialization.base import (
ImportError: cannot import name 'Encoding' from 'cryptography.hazmat.primitives.serialization.base' (/opt/pretix/test/lib/python3.9/site-packages/cryptography/hazmat/primitives/serialization/base.py)
```

**Comment by misters84** [comment]
Same problem here.

**Comment by raphaelm** [comment]
See https://github.com/pretix/pretix/issues/1930#issuecomment-781242156
