### ISSUE TITLE
Database migration after update to v3.17.1 fails

### ISSUE THREAD

**Issue by paviro** [pretix/pretix#2015]
**Describe the bug**
When trying to migrate the database after the update to v3.17.1 I got the attached error.

**Expected behaviour**
I expected the migration to finish.

**Logs**
```log
Operations to perform:
  Apply all migrations: auth, badges, banktransfer, contenttypes, oauth2_provider, otp_static, otp_totp, paypal, pretixapi, pretixbase, pretixdroid, pretixhelpers, pretixmultidomain, sessions, stripe, ticketoutputpdf
Running migrations:
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.ObjectInUse: FEHLER:  ALTER TABLE mit Relation »pretixbase_questionanswer« nicht möglich, weil es anstehende Trigger-Ereignisse dafür gibt


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/pretix/venv/lib/python3.7/site-packages/pretix/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 233, in handle
    fake_initial=fake_initial,
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/migrations/operations/models.py", line 525, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 384, in alter_unique_together
    self.execute(self._create_unique_sql(model, columns))
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: FEHLER:  ALTER TABLE mit Relation »pretixbase_questionanswer« nicht möglich, weil es anstehende Trigger-Ereignisse dafür gibt
```

**Comment by raphaelm** [comment]
Thank you and sorry for the hassle. We've hopefully fixed it and are now starting our pipeline to upload 3.17.2. Should be available in ~10 minutes, can you give us some feedback whether it helps before we announce it publicly?

**Comment by paviro** [comment]
Of course! Will test it and report as soon as its available. Thank you for the quick fix!

**Comment by raphaelm** [comment]
Now on PyPI. Docker Hub tends to take longer.

**Comment by paviro** [comment]
Seems to have worked now, thanks again! :)

**Comment by paviro** [comment]
Okay I get an internal server error now, let me check real quick.

**Comment by paviro** [comment]
```
CommandError: An error occurred during rendering /var/pretix/venv/lib/python3.7/site-packages/pretix/plugins/webcheckin/templates/pretixplugins/webcheckin/index.html: /usr/bin/env: „node“: Datei oder Verzeichnis nicht gefunden
```

Error on rebuild. Let me know if I should open a separate issue for this.

```
ERROR 2021-04-01 09:16:27,123 django.request log Internal Server Error: /control/
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/pretix/venv/lib/python3.7/site-packages/pretix/control/views/dashboards.py", line 634, in user_index
    return render(request, 'pretixcontrol/dashboard.html', ctx)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/compressor/templatetags/compress.py", line 143, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/var/pretix/venv/lib/python3.7/site-packages/compressor/templatetags/compress.py", line 97, in render_compressed
    return self.render_offline(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/compressor/templatetags/compress.py", line 82, in render_offline
    'is the original content:\n\n%s' % (key, original_content))
compressor.exceptions.OfflineGenerationError: You have offline compression enabled but key "8db6c6a918bbf763123433597ec01ef1dd55eed8dc91f99c76868ac8f3d1e7bc" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:


            <script type="text/javascript" src="/static/jquery/js/jquery-2.1.1.min.e40ec2161fe7.js"></script>
            <script type="text/javascript" src="/static/js/jquery.formset.5f6b62d88653.js"></script>
            <script type="text/javascript" src="/static/typeahead/typeahead.bundle.28654235b116.js"></script>
            <script type="text/javascript" src="/static/bootstrap/js/bootstrap.894d79839fac.js"></script>
            <script type="text/javascript" src="/static/moment/moment-with-locales.42d5c7ca492b.js"></script>
            <script type="text/javascript" src="/static/datetimepicker/bootstrap-datetimepicker.8d7293336e00.js"></script>
            <script type="text/javascript" src="/static/select2/select2.2f9a54c25009.js"></script>
            <script type="text/javascript" src="/static/select2/i18n/de.887bfc43e9d1.js"></script>
            <script type="text/javascript" src="/static/select2/i18n/en.a283e3dd0ae0.js"></script>
            <script type="text/javascript" src="/static/charts/raphael-min.06557bf5ef58.js"></script>
            <script type="text/javascript" src="/static/charts/morris.d995698f8d57.js"></script>
            <script type="text/javascript" src="/static/clipboard/clipboard.238dfb9a5014.js"></script>
            <script type="text/javascript" src="/static/rrule/rrule.e2d0f3efd7ed.js"></script>
            <script type="text/javascript" src="/static/pretixpresale/js/ui/questions.5cfc73204443.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/jquery.qrcode.min.05f0b1d7d4b9.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/clipboard.b4d8b9a54770.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/menu.3799201d46c7.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/sb-admin-2.18aa75419be1.js"></script>
		    <script type="text/javascript" src="/static/pretixcontrol/js/ui/main.91f464cd87d2.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/ui/quota.4a59c32426a9.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/ui/subevent.0b8675644778.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/ui/question.59fc7a62e356.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/ui/dragndroplist.1acc76c2d58f.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/ui/mail.7f14809f7883.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/ui/orderchange.f0a2bd4619c1.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/ui/typeahead.08b41cc756e4.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/ui/quicksetup.1a45b1ae40dc.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/ui/dashboard.f7b5dc5f61b0.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/ui/tabs.ccc044f45b99.js"></script>
            <script type="text/javascript" src="/static/leaflet/leaflet.386e649222d7.js"></script>
            <script type="text/javascript" src="/static/pretixcontrol/js/ui/geo.420bb02ca48a.js"></script>
            <script type="text/javascript" src="/static/pretixbase/js/details.6e7e42c5b669.js"></script>
            <script type="text/javascript" src="/static/pretixbase/js/asynctask.c8f050de8b75.js"></script>
            <script type="text/javascript" src="/static/sortable/Sortable.a4a0f1e33390.js"></script>
            <script type="text/javascript" src="/static/colorpicker/bootstrap-colorpicker.3b2dc9e3223c.js"></script>
            <script type="text/javascript" src="/static/fileupload/jquery.ui.widget.0b44270691b4.js"></script>
            <script type="text/javascript" src="/static/fileupload/jquery.fileupload.1a6f827f35e3.js"></script>
            <script type="text/javascript" src="/static/lightbox/js/lightbox.min.db3e1524e9f2.js"></script>
            <script type="text/javascript" src="/static/are-you-sure/jquery.are-you-sure.4842acab6887.js"></script>
```

Probably not related?

**Comment by raphaelm** [comment]
You probably do not have node.js installed, which is required as of 3.17 (except for pure-wheel installs), see release blogpost:
https://pretix.eu/about/en/blog/20210331-release-3170/

**Comment by paviro** [comment]
Ah shoot my bad sorry!

**Comment by paviro** [comment]
Everything good 👍🏼
