### ISSUE TITLE
pretix fails to delete personal data if order contains file upload question

### ISSUE THREAD

**Issue by mistressofjellyfish** [pretix/pretix#2016]
So this was noticed with an event created under pretix 3.5.0 and finally handled with 3.17.2.

**Describe the bug**
If an order contains a file upload question, shredding of the personal data yields an unexpected error. In my server logs, I see this exception:

```
[2021-04-02 18:12:14,470: ERROR/ForkPoolWorker-1] Task pretix.base.services.shredder.export[e0c23069-7b4d-419a-a1bd-0fd97b2045fd] raised unexpected: KeyError('request')
 Traceback (most recent call last):
   File "/var/pretix/venv/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
     R = retval = fun(*args, **kwargs)
   File "/var/pretix/venv/lib/python3.7/site-packages/pretix/base/services/tasks.py", line 41, in __call__
     ret = super().__call__(*args, **kwargs)
   File "/var/pretix/venv/lib/python3.7/site-packages/pretix/base/services/tasks.py", line 87, in __call__
     ret = super().__call__(*args, **kwargs)
   File "/var/pretix/venv/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
     return self.run(*args, **kwargs)
   File "/var/pretix/venv/lib/python3.7/site-packages/pretix/base/services/shredder.py", line 49, in export
     for fname, ftype, content in it:
   File "/var/pretix/venv/lib/python3.7/site-packages/pretix/base/shredder.py", line 329, in generate_files
     for op in OrderPosition.all.filter(order__event=self.event).prefetch_related('answers')
   File "/var/pretix/venv/lib/python3.7/site-packages/pretix/base/shredder.py", line 329, in <dictcomp>
     for op in OrderPosition.all.filter(order__event=self.event).prefetch_related('answers')
   File "/var/pretix/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 760, in data
     ret = super().data
   File "/var/pretix/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 260, in data
     self._data = self.to_representation(self.instance)
   File "/var/pretix/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 678, in to_representation
     self.child.to_representation(item) for item in iterable
   File "/var/pretix/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 678, in <listcomp>
     self.child.to_representation(item) for item in iterable
   File "/var/pretix/venv/lib/python3.7/site-packages/pretix/api/serializers/order.py", line 135, in to_representation
     }, request=self.context['request'])
```

**Expected behavior**
The UI should take me to the next step, downloading the data before purging.

**Additional context**
This seems to be related to data collection being a background task and thus reversing the URL for the file part of the answer fails, because no request is attached; but I do not understand the codebase well enough to qualify for more than an educated guess as to why `self.context` has no key `request`.

**Comment by raphaelm** [comment]
The  log excerpt seems to be missing the error message itself (should be above), can you paste that? I have a suspicion though, you're most likely correct with your guess.

**Comment by mistressofjellyfish** [comment]
Ah, I missed copying that line. Yes, it's basically a key error. I edited the issue to include the missing line. In any case, here it is:

`[2021-04-02 18:12:14,470: ERROR/ForkPoolWorker-1] Task pretix.base.services.shredder.export[e0c23069-7b4d-419a-a1bd-0fd97b2045fd] raised unexpected: KeyError('request')`
