### ISSUE TITLE
Duplicate Column names while migration [Fresh install, 3.18/3.16]

### ISSUE THREAD

**Issue by Corinari** [pretix/pretix#2076]
**Describe the bug**
While using "python -m pretix migrate", pretix sends following error:
django.db.utils.OperationalError: (1060, "Duplicate column name 'generate_tickets'")

I was following your Docu [here](https://pretix.readthedocs.io/en/stable/admin/installation/manual_smallscale.html)

**Expected behavior**
Migrate should running fine

**Additional context**
Dropping the Columns in the tables did help momentarily, but only more tables showed duplicated entries. 
Full Error message:
`
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/var/pretix/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/var/pretix/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/var/pretix/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1060, "Duplicate column name 'generate_tickets'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/pretix/venv/lib/python3.8/site-packages/pretix/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 110, in database_forwards
    schema_editor.add_field(
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/backends/mysql/schema.py", line 80, in add_field
    super().add_field(model, field)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 482, in add_field
    self.execute(sql, params)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/var/pretix/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/var/pretix/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/var/pretix/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1060, "Duplicate column name 'generate_tickets'")
`

**Comment by raphaelm** [comment]
I just did the very minimum install of pretix with SQLite in a clean environment, and it did not raise any issue, so this doesn't seem to be a general problem with the release:

```
pip install pretix
python -m pretix migrate
```

I therefore assume something is odd in your setup. Can you try dropping the mysql database entirely and run migrations from the start again?

**Comment by Corinari** [comment]
Hi Raphael, 

i already dropped the whole database and even tried reinstalling it on fresh VMs. Always the same error. 
It also required me to install mysqlclient (via pip), maybe here was a error. 

I was able to install pretix via postgresql, which is fine with me for testing. 
if you dont mind, i would close this issue.

Thank you for your quick respose and help

**Comment by raphaelm** [comment]
I've tried myself on MySQL now as well without any issues, so I'm closing for now, and will reopen if someone else experiences the same problem.
