### ISSUE TITLE
AttributeError: 'CountryField' object has no attribute 'db_collation'

### ISSUE THREAD

**Issue by sborja** [pretix/pretix#2127]
Hi,

I'm trying to upgrade my self hosted pretix installation from version 3.12 to the last version (now 4.0.0).

I'm following steps for manual deployment as is described on documentation:

$ source /var/pretix/venv/bin/activate
(venv)$ pip3 install -U pretix[postgres] gunicorn
(venv)$ python -m pretix migrate
(venv)$ python -m pretix rebuild
(venv)$ python -m pretix updatestyles
# systemctl restart pretix-web pretix-worker

But i have an error with "migrate" step.

This is full report for error:

 Apply all migrations: auth, badges, banktransfer, contenttypes, oauth2_provider, otp_static, otp_totp, paypal, pretixapi, pretixbase, pretixdroid, pretixhelpers, pretixmultidomain, sessions, stripe, ticketoutputpdf
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/pretix/venv/lib/python3.7/site-packages/pretix/__main__.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 201, in handle
    pre_migrate_state = executor._create_project_state(with_applied_migrations=True)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 79, in _create_project_state
    migration.mutate_state(state, preserve=False)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/migrations/migration.py", line 89, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 88, in state_forwards
    field = self.field.clone()
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 512, in clone
    name, path, args, kwargs = self.deconstruct()
  File "/var/pretix/venv/lib/python3.7/site-packages/django_countries/fields.py", line 343, in deconstruct
    name, path, args, kwargs = super().deconstruct()
  File "/var/pretix/venv/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 1089, in deconstruct
    if self.db_collation:
AttributeError: 'CountryField' object has no attribute 'db_collation'

Could you help me with this issue?

Thanks in advance.

**Comment by sborja** [comment]
I found the solution for my error, I need to upgrade django-countries...

But know, i have another error in "rebuild" step:

CommandError: An error occurred during rendering /var/pretix/venv/lib/python3.7/site-packages/pretix/plugins/webcheckin/templates/pretixplugins/webcheckin/index.html: /usr/bin/env: ‘node’: No such file or directory

Could you help me with this?

Thansk in advance

**Comment by raphaelm** [comment]
Please install nodejs and npm :)
