### ISSUE TITLE
Internal server error after upgrade from 3.15 to 4.3

### ISSUE THREAD

**Issue by AgentSmith83** [pretix/pretix#2230]
I followed these general steps to upgrade our instance of pretix:
$ source /var/pretix/venv/bin/activate
(venv)$ pip3 install -U pretix[mysql] gunicorn --no-cache-dir 
(venv)$ python -m pretix migrate
(venv)$ python -m pretix rebuild
(venv)$ python -m pretix updatestyles
# systemctl restart pretix-web pretix-worker

During the upgrade I noticed a few error messages:

Invalid template /var/pretix/venv/lib/python3.7/site-packages/django_otp/templates/otp/admin19/login.html: 'admin_static' is not a registered tag library. Must be one of:

Error parsing template /var/pretix/venv/lib/python3.7/site-packages/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_form.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/django_otp/plugins/otp_totp/templates/otp_totp/admin/config.html: admin/base_site.html
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_assign.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/refund_export.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/job_detail.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/django_otp/templates/otp/admin30/login.html: admin/base_site.html
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/sepa_export.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.

CommandError: An error occurred during rendering /var/pretix/venv/lib/python3.7/site-packages/pretix/control/templates/pretixcontrol/checkin/list_edit.html: /usr/bin/env: ‘node’: No such file or directory

pretixbase.RevokedTicketSecret.secret: (fields.W162) MariaDB does not support a database index on longtext columns.
        HINT: An index won't be created. Silence this warning if you don't care about it.

After this when I went to the website It is now showing the error message "Internal Server Error".

I then checked pretix.log in /var/pretix/data/logs and noticed some new errors, not sure if they are related or not:

ERROR 2021-09-29 21:45:11,288 django.request log Internal Server Error: /StMarysRD/
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
 File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/compressor/templatetags/compress.py", line 143, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/var/pretix/venv/lib/python3.7/site-packages/compressor/templatetags/compress.py", line 97, in render_compressed
    return self.render_offline(context)
  File "/var/pretix/venv/lib/python3.7/site-packages/compressor/templatetags/compress.py", line 82, in render_offline
    'is the original content:\n\n%s' % (key, original_content))
compressor.exceptions.OfflineGenerationError: You have offline compression enabled but key "05a17107d3fec4f92f0dabeda19f8b4235c09d46b21e4f58beeaee3a46aaff32" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:

    <script type="text/javascript" src="/static/jquery/js/jquery-2.1.1.min.e40ec2161fe7.js"></script>
    <script type="text/javascript" src="/static/moment/moment-with-locales.42d5c7ca492b.js"></script>
    <script type="text/javascript" src="/static/moment/moment-timezone-with-data-1970-2030.b1fb3f60f3f0.js"></script>
    <script type="text/javascript" src="/static/js/jquery.formset.5f6b62d88653.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.894d79839fac.js"></script>
    <script type="text/javascript" src="/static/datetimepicker/bootstrap-datetimepicker.8d7293336e00.js"></script>
    <script type="text/javascript" src="/static/slider/bootstrap-slider.e2a09e29ed62.js"></script>
    <script type="text/javascript" src="/static/cropper/cropper.6d012e5ad5c8.js"></script>
    <script type="text/javascript" src="/static/pretixbase/js/details.04883e4ec180.js"></script>
    <script type="text/javascript" src="/static/pretixcontrol/js/jquery.qrcode.min.05f0b1d7d4b9.js"></script>
    <script type="text/javascript" src="/static/pretixpresale/js/widget/floatformat.4af1b92ceecf.js"></script>
    <script type="text/javascript" src="/static/pretixpresale/js/ui/questions.f2b362c8fae4.js"></script>
    <script type="text/javascript" src="/static/pretixpresale/js/ui/main.61b3b5411364.js"></script>
    <script type="text/javascript" src="/static/pretixbase/js/asynctask.e30270c0eca6.js"></script>
    <script type="text/javascript" src="/static/pretixpresale/js/ui/cart.f9b4b3cc7289.js"></script>
    <script type="text/javascript" src="/static/lightbox/js/lightbox.min.db3e1524e9f2.js"></script>
    <script type="text/javascript" src="/static/pretixpresale/js/ui/iframe.cd4655c4dfd4.js"></script>

Any help resolving this issue is appreciated as the site is currently offline.

**Comment by raphaelm** [comment]
You do not have nodejs installed. Please install nodejs and npm and retry the update steps :)
