### ISSUE TITLE
Internal Server Error psycopg2.errors.UndefinedColumn: column pretixbase_event.last_modified does not exist

### ISSUE THREAD

**Issue by sfo-md** [pretix/pretix#2430]
Hi,

I just updated pretix to 4.5.0 and after restart the logs shows the following:

```
ERROR 2022-01-25 19:54:55,061 django.request log Internal Server Error: /mcs/MC-220319/
Traceback (most recent call last):
  File "/opt/pretix/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column pretixbase_event.last_modified does not exist
LINE 1: ...subevents", "pretixbase_event"."seating_plan_id", "pretixbas...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pretix/.venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/pretix/.venv/lib/python3.8/site-packages/pretix/presale/middleware.py", line 67, in __call__
    redirect = _detect_event(request, require_live=url.url_name not in self.NO_REQUIRE_LIVE_URLS)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/pretix/.venv/lib/python3.8/site-packages/pretix/presale/utils.py", line 193, in _detect_event
    request.event = Event.objects\
  File "/opt/pretix/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/opt/pretix/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/opt/pretix/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/pretix/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/pretix/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/pretix/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/pretix/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/pretix/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/pretix/.venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/pretix/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column pretixbase_event.last_modified does not exist
LINE 1: ...subevents", "pretixbase_event"."seating_plan_id", "pretixbas...
                                                             ^
```

Versions used:
PostgreSQL Version 12.9
Python 3.8.10

What can I do about this?

**Comment by raphaelm** [comment]
pretty sure you did not execute all steps of the upgrade process :)
