### ISSUE TITLE
make production fails in current pretix/standalone:stable docker container

### ISSUE THREAD

**Issue by stapelberg** [pretix/pretix#2570]
**Describe the bug**

I’m using the following Dockerfile:

```
FROM pretix/standalone:stable
USER root
RUN pip3 install pretix-saferpay
USER pretixuser
RUN cd /pretix/src && make production
```

When I build it, I get:
```
DOCKER_BUILDKIT=1 docker pull pretix/standalone:stable
stable: Pulling from pretix/standalone
Digest: sha256:24aa036b28f84818b4e757e121d60770155037753292fd05b53bd1cc85c6ea14
Status: Image is up to date for pretix/standalone:stable
docker.io/pretix/standalone:stable
DOCKER_BUILDKIT=1 docker build --no-cache . -t stapelberg/pretix-saferpay
[+] Building 9.7s (6/6) FINISHED                                                                                                                                                                         
 => [internal] load build definition from Dockerfile                                                                                                                                                0.0s
 => => transferring dockerfile: 37B                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/pretix/standalone:stable                                                                                                                                 0.0s
 => CACHED [1/3] FROM docker.io/pretix/standalone:stable                                                                                                                                            0.0s
 => [2/3] RUN pip3 install pretix-saferpay                                                                                                                                                          0.8s
 => ERROR [3/3] RUN cd /pretix/src && make production                                                                                                                                               8.9s
------                                                                                                                                                                                                   
 > [3/3] RUN cd /pretix/src && make production:                                                                                                                                                          
#6 0.223 ./manage.py compilemessages                                                                                                                                                                     
#6 1.043 File “/pretix/src/pretix/locale/nl/LC_MESSAGES/django.po” is already compiled and up to date.                                                                                                   
#6 1.043 File “/pretix/src/pretix/locale/nl/LC_MESSAGES/djangojs.po” is already compiled and up to date.                                                                                                 
#6 1.043 File “/pretix/src/pretix/locale/pt_PT/LC_MESSAGES/django.po” is already compiled and up to date.                                                                                                
#6 1.043 File “/pretix/src/pretix/locale/pt_PT/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/fi/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/fi/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/pt_BR/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/pt_BR/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/pl/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/pl/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/pl_Informal/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/pl_Informal/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/el/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/el/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/gl/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/gl/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/sl/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/sl/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/ar/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/ar/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/he/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/he/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/ja/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/ja/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/cs/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/cs/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/uk/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/uk/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/ca/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/ca/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/tr/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/tr/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/de_Informal/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/de_Informal/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/nl_Informal/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/nl_Informal/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/sv/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/sv/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/it/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/it/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/hu/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/hu/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/nb_NO/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/nb_NO/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/de/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/lv/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/lv/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/nl_BE/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/nl_BE/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/zh_Hans/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/zh_Hans/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/pt/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/pt/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/ru/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/ru/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/es/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/es/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/si/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/si/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/ro/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/ro/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/da/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/da/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/fr/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/pretix/locale/fr/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/nl/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/nl/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/pt_PT/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/pt_PT/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/fi/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/fi/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/pt_BR/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/pt_BR/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/pl/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/pl/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/pl_Informal/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/pl_Informal/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/el/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.043 File “/pretix/src/build/lib/pretix/locale/el/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/gl/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/gl/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/sl/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/sl/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/ar/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/ar/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/he/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/he/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/ja/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/ja/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/cs/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/cs/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/uk/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/uk/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/ca/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/ca/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/tr/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/tr/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/de_Informal/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/de_Informal/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/nl_Informal/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/nl_Informal/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/sv/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/sv/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/it/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/it/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/hu/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/hu/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/nb_NO/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/nb_NO/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/de/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/lv/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/lv/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/nl_BE/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/nl_BE/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/zh_Hans/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/zh_Hans/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/pt/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/pt/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/ru/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/ru/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/es/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/es/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/si/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/si/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/ro/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/ro/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/da/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/da/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/fr/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/locale/fr/LC_MESSAGES/djangojs.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/build/lib/pretix/helpers/locale/de_Informal/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.044 File “/pretix/src/pretix/helpers/locale/de_Informal/LC_MESSAGES/django.po” is already compiled and up to date.
#6 1.185 ./manage.py compilejsi18n
#6 2.034 processing language en
#6 2.034 processing language de
#6 2.034 processing language de-informal
#6 2.034 processing language ar
#6 2.034 processing language zh-hans
#6 2.034 processing language da
#6 2.034 processing language nl
#6 2.034 processing language nl-informal
#6 2.034 processing language fr
#6 2.034 processing language el
#6 2.034 processing language it
#6 2.034 processing language lv
#6 2.034 processing language pt-pt
#6 2.034 processing language ru
#6 2.034 processing language es
#6 2.034 processing language tr
#6 2.182 ./manage.py collectstatic --noinput
#6 3.011 
#6 3.011 17 static files copied to '/pretix/src/pretix/static.dist', 928 unmodified, 33 post-processed.
#6 3.150 # keep this in sync with setup.py!
#6 3.150 mkdir -p pretix/static.dist/node_prefix/
#6 3.151 cp -r pretix/static/npm_dir/* pretix/static.dist/node_prefix/
#6 3.152 npm install --prefix=pretix/static.dist/node_prefix
#6 3.178 npm does not support Node.js v15.14.0
#6 3.178 You should probably upgrade to a newer version of node as we
#6 3.178 can't make any promises that npm will work with this version.
#6 3.178 You can find the latest version at https://nodejs.org/
#6 3.415 npm WARN old lockfile 
#6 3.415 npm WARN old lockfile The package-lock.json file was created with an old version of npm,
#6 3.415 npm WARN old lockfile so supplemental metadata must be fetched from the registry.
#6 3.415 npm WARN old lockfile 
#6 3.415 npm WARN old lockfile This is a one-time fix-up, please be patient...
#6 3.415 npm WARN old lockfile 
#6 6.034 
#6 6.034 up to date, audited 443 packages in 3s
#6 6.034 
#6 6.034 15 packages are looking for funding
#6 6.034   run `npm fund` for details
#6 6.037 
#6 6.037 6 vulnerabilities (4 moderate, 2 high)
#6 6.037 
#6 6.037 To address all issues, run:
#6 6.037   npm audit fix
#6 6.037 
#6 6.037 Run `npm audit` for details.
#6 6.045 ./manage.py compress
#6 8.539 Traceback (most recent call last):
#6 8.539   File "/pretix/src/./manage.py", line 31, in <module>
#6 8.539     execute_from_command_line(sys.argv)
#6 8.539   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
#6 8.539     utility.execute()
#6 8.539   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
#6 8.539 Compressing... Invalid template /usr/local/lib/python3.9/site-packages/django_filters/templates/django_filters/rest_framework/crispy_form.html: 'crispy_forms_tags' is not a registered tag library. Must be one of:
#6 8.539 bootstrap3
#6 8.539 cache
#6 8.539 cache_large
#6 8.539 captureas
#6 8.539 classname
#6 8.539 commadecimal
#6 8.539 compress
#6 8.539 countries
#6 8.539 date_fast
#6 8.539 debugger_tags
#6 8.539 dotdecimal
#6 8.539 escapejson
#6 8.539 eventsignal
#6 8.539 eventurl
#6 8.539 expiresformat
#6 8.539 formset_tags
#6 8.539 getitem
#6 8.539 hierarkey_form
#6 8.539 highlighting
#6 8.539 hijack
#6 8.539 humanize
#6 8.539 i18n
#6 8.539 ibanformat
#6 8.539 indent_text
#6 8.539 l10n
#6 8.539 lists
#6 8.539 mail_settings_preview
#6 8.539 markup_tags
#6 8.539 money
#6 8.539 oneline
#6 8.539 order_overview
#6 8.539 phone_format
#6 8.539 rest_framework
#6 8.539 rich_text
#6 8.539 safelink
#6 8.539 static
#6 8.539 statici18n
#6 8.539 syntax_color
#6 8.539 thumb
#6 8.539 tz
#6 8.539 unidecode
#6 8.539 urlreplace
#6 8.539 widont
#6 8.539 Error parsing template /pretix/src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_assign.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
#6 8.539 Error parsing template /pretix/src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/sepa_export.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
#6 8.539 Error parsing template /usr/local/lib/python3.9/site-packages/django_otp/plugins/otp_totp/templates/otp_totp/admin/config.html: admin/base_site.html
#6 8.539 Error parsing template /pretix/src/pretix/control/templates/pretixcontrol/email_setup_smtp.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
#6 8.539 Error parsing template /pretix/src/pretix/control/templates/pretixcontrol/email_setup.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
#6 8.539 Error parsing template /pretix/src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_form.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
#6 8.539 Error parsing template /pretix/src/pretix/control/templates/pretixcontrol/email_setup_simple.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
#6 8.539 Error parsing template /pretix/src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/refund_export.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
#6 8.539 Error parsing template /pretix/src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/job_detail.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
#6 8.539 Error parsing template /usr/local/lib/python3.9/site-packages/django_otp/templates/otp/admin111/login.html: admin/base_site.html
#6 8.539     self.fetch_command(subcommand).run_from_argv(self.argv)
#6 8.539   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
#6 8.539     self.execute(*args, **cmd_options)
#6 8.539   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
#6 8.540     output = self.handle(*args, **options)
#6 8.540   File "/usr/local/lib/python3.9/site-packages/compressor/management/commands/compress.py", line 277, in handle
#6 8.540     self.handle_inner(**options)
#6 8.540   File "/usr/local/lib/python3.9/site-packages/compressor/management/commands/compress.py", line 300, in handle_inner
#6 8.540     offline_manifest, block_count, results = self.compress(engine, extensions, verbosity, follow_links, log)
#6 8.540   File "/usr/local/lib/python3.9/site-packages/compressor/management/commands/compress.py", line 225, in compress
#6 8.540     rendered = parser.render_nodelist(template, context, node)
#6 8.540   File "/usr/local/lib/python3.9/site-packages/compressor/offline/django.py", line 114, in render_nodelist
#6 8.540     return node.nodelist.render(context)
#6 8.540   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
#6 8.540     bit = node.render_annotated(context)
#6 8.540   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
#6 8.540     return self.render(context)
#6 8.540   File "/usr/local/lib/python3.9/site-packages/django/templatetags/static.py", line 106, in render
#6 8.540     url = self.url(context)
#6 8.540   File "/usr/local/lib/python3.9/site-packages/django/templatetags/static.py", line 103, in url
#6 8.540     return self.handle_simple(path)
#6 8.540   File "/usr/local/lib/python3.9/site-packages/django/templatetags/static.py", line 118, in handle_simple
#6 8.540     return staticfiles_storage.url(path)
#6 8.540   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 147, in url
#6 8.540     return self._url(self.stored_name, name, force)
#6 8.540   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 126, in _url
#6 8.540     hashed_name = hashed_name_func(*args)
#6 8.540   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 417, in stored_name
#6 8.540     raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
#6 8.540 ValueError: Missing staticfiles manifest entry for 'jquery/js/jquery-3.4.1.min.js'
#6 8.906 make: *** [Makefile:16: compress] Error 1
------
executor failed running [/bin/sh -c cd /pretix/src && make production]: exit code: 2
make: *** [Makefile:7: update] Error 1
```

**Comment by alexjsteffen** [comment]
@stapelberg I had the same issue with the self-hosted manual install. Turns out it was the **pretix-saferpay** plugin that was giving the error. I found the one page that referenced jquery and it lead me there. So a change in the Dockerfile may be needed. :)

**Comment by stapelberg** [comment]
Ah, so this issue should probably be moved to the https://github.com/pretix/pretix-saferpay/ repository, then (cc @raphaelm)

When I use `RUN pip3 install pretix-saferpay==1.3.0`, everything works. Looks like the issue appeared between 1.3.0 and 1.3.1 (current release).

**Comment by raphaelm** [comment]
Interesting :eyes: 

In pretix-saferpay 1.3.1, basically nothing substantial changed, just translation, meta data and an exception handler:

https://github.com/pretix/pretix-saferpay/compare/v1.3.0...v1.3.1

The error message complains about missing jQuery 3.4, but pretix-saferpay does not refer to this version:

https://github.com/pretix/pretix-saferpay/blob/11be0d4e1972f336d2aa91cf66f4af9424881575/pretix_saferpay/templates/pretix_saferpay/redirect.html#L12

So I'm not yet 100% sure if this is actually caused by pretix-saferpay or just by "any plugin being installed". But why would saferpay 1.3.0 work then? Very confusing :thinking: 

The stacktrace looks like being caused by ``django_otp/templates/otp/admin111/login.html``, which is a template from a third-party library from which we do not use any templates, but I don't get how that failure depends on the version of pretix-saferpay. In any case, if django-otp actually *is* the issue, #2459 might help.

**Comment by git-eri** [comment]
@stapelberg What was your solution for this problem? Like ten days ago i successfully installed and setup pretix but now i have no solution as i get the same django related error while "migrating" and the installation is broken

**Comment by raphaelm** [comment]
Can you try pretix:latest instead of pretix:stable just as a test? We fixed both the mysql issue as well as upgraded compressor on master this week.

**Comment by stapelberg** [comment]
With `pretix:latest`, the Dockerfile works for me again (with saferpay 1.3.1). Thanks!

**Comment by git-eri** [comment]
@raphaelm When is the fix being applied to pip? Still having trouble to set up the small-scale manual deployment

**Comment by raphaelm** [comment]
Probably not before our next regular stable release, which usually happens at the end of every month. A quicker fix on the stable branch would involve backporting a dependency upgrade which could have bad side effects so we usually avoid that.

You already figured out how to downgrad django-mysql. For the other issue, can you try writing your dockerfile in a way that just ignores the exit code of `make production`, eg by doing `make production || true`. If we're lucky, pretix might run just fine.

**Comment by git-eri** [comment]
@raphaelm going for the docker deployment with tag stable worked fine for me for now, only the manual deployment (using the tutorial in the wiki) is broken. Just the vanilla installation is broken, tried both ubuntu 20.04 and 22.04 both with psql/mariadb

**Comment by raphaelm** [comment]
The non-docker installation has shown the error with the non-parseable templates for a very long time but worked just fine if you just ignored the output and continued with the next step. Not nice, but the bug's not caused by us and there were no major consequences. This issue was about the docker build process where ignoring the output is less of a possibility.
