### ISSUE TITLE
Unknown column 'pretixbase_device.info' in 'field list'

### ISSUE THREAD

**Issue by Cheatha** [pretix/pretix#2655]
**Describe the bug**
Opening the backend causes an internal server error. »Veranstaltungsprotokoll« just shows a spinning wheel. journalctl says: `Unknown column 'pretixbase_device.info' in 'field list'`

**Expected behavior**
No internal server error ;)

**Screenshots**
```
Mai 17 12:55:08 pretix gunicorn[668]: MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'pretixbase_device.info' in 'field list'")
Mai 17 12:55:08 pretix gunicorn[668]: The above exception was the direct cause of the following exception:
Mai 17 12:55:08 pretix gunicorn[668]: Traceback (most recent call last):
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
Mai 17 12:55:08 pretix gunicorn[668]:     response = get_response(request)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
Mai 17 12:55:08 pretix gunicorn[668]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/pretix/control/views/dashboards.py", line 445, in event_index_log_lazy
Mai 17 12:55:08 pretix gunicorn[668]:     return render(
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
Mai 17 12:55:08 pretix gunicorn[668]:     content = loader.render_to_string(template_name, context, request, using=using)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
Mai 17 12:55:08 pretix gunicorn[668]:     return template.render(context, request)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
Mai 17 12:55:08 pretix gunicorn[668]:     return self.template.render(context)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
Mai 17 12:55:08 pretix gunicorn[668]:     return self._render(context)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
Mai 17 12:55:08 pretix gunicorn[668]:     return self.nodelist.render(context)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
Mai 17 12:55:08 pretix gunicorn[668]:     bit = node.render_annotated(context)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
Mai 17 12:55:08 pretix gunicorn[668]:     return self.render(context)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 171, in render
Mai 17 12:55:08 pretix gunicorn[668]:     len_values = len(values)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/db/models/query.py", line 262, in __len__
Mai 17 12:55:08 pretix gunicorn[668]:     self._fetch_all()
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
Mai 17 12:55:08 pretix gunicorn[668]:     self._result_cache = list(self._iterable_class(self))
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
Mai 17 12:55:08 pretix gunicorn[668]:     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
Mai 17 12:55:08 pretix gunicorn[668]:     cursor.execute(sql, params)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
Mai 17 12:55:08 pretix gunicorn[668]:     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
Mai 17 12:55:08 pretix gunicorn[668]:     return executor(sql, params, many, context)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
Mai 17 12:55:08 pretix gunicorn[668]:     return self.cursor.execute(sql, params)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
Mai 17 12:55:08 pretix gunicorn[668]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
Mai 17 12:55:08 pretix gunicorn[668]:     return self.cursor.execute(sql, params)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
Mai 17 12:55:08 pretix gunicorn[668]:     return self.cursor.execute(query, args)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
Mai 17 12:55:08 pretix gunicorn[668]:     res = self._query(query)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
Mai 17 12:55:08 pretix gunicorn[668]:     db.query(q)
Mai 17 12:55:08 pretix gunicorn[668]:   File "/var/pretix/venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
Mai 17 12:55:08 pretix gunicorn[668]:     _mysql.connection.query(self, query)
Mai 17 12:55:08 pretix gunicorn[668]: django.db.utils.OperationalError: (1054, "Unknown column 'pretixbase_device.info' in 'field list'")
```

**Additional context**
I'm running v4.*9*.0 on a manual installation with MariaDBand did an upgrade with this command: 

```
source /var/pretix/venv/bin/activate
/var/pretix/venv/bin/python3 -m pip install --upgrade pip
pip3 install -U --upgrade-strategy eager pretix gunicorn
python -m pretix migrate
python -m pretix rebuild
python -m pretix updatestyles
systemctl restart pretix-web pretix-worker
```

My upgrade-check says the newest Version is 4.*8*.0. Maybe the latest update did go wrong and some database migrations weren't made. Running the commands again show this error: 

```
WARNINGS:
pretixbase.RevokedTicketSecret.secret: (fields.W162) MariaDB does not support a database index on longtext columns.
        HINT: An index won't be created. Silence this warning if you don't care about it.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/pretix/venv/lib/python3.9/site-packages/pretix/__main__.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretix/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/pretix/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/pretix/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/pretix/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/pretix/venv/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/pretix/venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 92, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/var/pretix/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/var/pretix/venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/var/pretix/venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 214, in build_graph
    self.load_disk()
  File "/var/pretix/venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 116, in load_disk
    migration_module = import_module(migration_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/pretix/venv/lib/python3.9/site-packages/pretix/base/migrations/0102_auto_20181017_0024.py", line 7, in <module>
    from django_mysql.utils import connection_is_mariadb
ImportError: cannot import name 'connection_is_mariadb' from 'django_mysql.utils' (/var/pretix/venv/lib/python3.9/site-packages/django_mysql/utils.py)
```

**Comment by choseh** [comment]
Apparently django-mysql dropped "connection_is_mariadb" with version 4.6.0

https://github.com/adamchainz/django-mysql/blob/main/src/django_mysql/models/fields/dynamic.py

I installed 4.5.0 with
`pip install django-mysql==4.5.0`

and the error is gone.

**Comment by Cheatha** [comment]
Thanks! I've installed this specific version and re-run the migrations, now the proble is gone! :)

```
source /var/pretix/venv/bin/activate
pip3 install django-mysql==4.5.0
python -m pretix migrate           
python -m pretix rebuild
python -m pretix updatestyles
systemctl restart pretix-web pretix-worker
```
