### ISSUE TITLE
Web checkin throws ISE

### ISSUE THREAD

**Issue by augustin** [pretix/pretix#2797]
**Describe the bug**
Clicking on a ticket in the web checkin system throws an error 500.

**Screenshots**
![image](https://user-images.githubusercontent.com/13209080/190498868-fee050fe-5dd6-4cce-8052-670592fd8f89.png)

**Additional context**
```
ERROR 2022-09-15 19:58:36,321 django.request log Internal Server Error: /api/v1/organizers/<ORGANIZER>/events/<EVENT>/checkinlists/4/positions/623/redeem/
Traceback (most recent call last):
File "~/venv.pretix/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
	response = get_response(request)
File "~/venv.pretix/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
	response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "~/venv.pretix/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
	return view_func(*args, **kwargs)
File "~/venv.pretix/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
	return self.dispatch(request, *args, **kwargs)
File "~/venv.pretix/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
	response = self.handle_exception(exc)
File "~/venv.pretix/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
	self.raise_uncaught_exception(exc)
File "~/venv.pretix/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
	raise exc
File "~/venv.pretix/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
	response = handler(request, *args, **kwargs)
File "~/venv.pretix/lib/python3.9/site-packages/pretix/api/views/checkin.py", line 539, in redeem
	perform_checkin(
File "~/venv.pretix/lib/python3.9/site-packages/pretix/base/services/checkin.py", line 652, in perform_checkin
	reason = _logic_explain(clist.rules, op.subevent or clist.event, rule_data)
File "~/venv.pretix/lib/python3.9/site-packages/pretix/base/services/checkin.py", line 245, in _logic_explain
	min_weight = min(path_weights)
ValueError: min() arg is an empty sequence
```

**Comment by augustin** [comment]
Note this is with an older version (4.7.1), I don't want to upgrade only a week before the event. However I did look at the commit logs for the relevant files and I don't see any changes which would affect this...

**Comment by raphaelm** [comment]
Well that is quite old and I wouldn't be sure if it's fixed or not, but anyways this will be hard to debug without the data. At the very least, the JSON representation of the custom rules of the check-in list would probably be required for reproducing it.

**Comment by augustin** [comment]
We do not have any custom rules.

![image](https://user-images.githubusercontent.com/13209080/190542988-4c1b5759-5631-4268-b168-4c6b16768d62.png)

**Comment by augustin** [comment]
It is worth noting that for unpaid orders I do get the "not paid!" screen, but for any paid tickets, this is what happens.

Historically we do checkin on paper for this event so it is not really a big deal if we cannot go all-digital this year (we also need to see ticket details, which the checkin system in Pretix doesn't seem to have, so that may be another reason we just stick with past procedure.)

**Comment by raphaelm** [comment]
> We do not have any custom rules.

Technically you probably do as the screenshot looks. You have an empty rule of `OR` instead of a really empty rule. This has in fact been fixed in newer pretix versions. Workaround without update would probably be to clear that field via database or API.

**Comment by augustin** [comment]
Indeed, that fixed it, thanks!
