### ISSUE TITLE
Server Error on Installation

### ISSUE THREAD

**Issue by martrobb** [pretix/pretix#2908]
![image](https://user-images.githubusercontent.com/117538893/201999303-943552fd-cb3c-4ef8-bc98-29ccccbc8693.png)

Hey! I've installed Pretix via the Docker installation guide on Docker 10.0 but seem to be getting this error. You can see in the screenshot attached, I've not setup anything on the website yet. Installed it and this is displaying.

Urgent Help if possible please.

**Comment by raphaelm** [comment]
please see https://docs.pretix.eu/en/latest/admin/errors.html

**Comment by martrobb** [comment]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/pretix/src/pretix/base/middleware.py", line 248, in process_response
    if gs.settings.leaflet_tiles:
  File "/usr/local/lib/python3.9/site-packages/hierarkey/proxy.py", line 181, in __getattr__
    return self.get(key)
  File "/usr/local/lib/python3.9/site-packages/hierarkey/proxy.py", line 162, in get
    if key in self._cache():
  File "/usr/local/lib/python3.9/site-packages/hierarkey/proxy.py", line 47, in _cache
    self._cached_obj = cache.get_or_set(
  File "/usr/local/lib/python3.9/site-packages/django/core/cache/backends/base.py", line 173, in get_or_set
    default = default()
  File "/usr/local/lib/python3.9/site-packages/hierarkey/proxy.py", line 49, in <lambda>
    lambda: {s.key: s.value for s in self._objects.all()},
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?`

**Comment by martrobb** [comment]
This is the error in the pretix.log, nothing about nodejs or anything

**Comment by raphaelm** [comment]
pretix can't find your PostgreSQL server. Most likely your configuration file is in the wrong place
