### ISSUE TITLE
python manage.py dumpdata fails with an exception

### ISSUE THREAD

**Issue by stapelberg** [pretix/pretix#3165]
### Problem and impact

I want to run a copy of the live shop system on my local PC for testing/development purposes.

On the internet, I read that django apps have a dumpdata and loaddata command, which sounds exactly like the right fit (the live instance runs with PostgreSQL, the local dev instance runs with SQLite).

But, when running `dumpdata` on pretix 4.17.1, I get the following error:

```
# docker exec -ti pretix.service bash
pretixuser@3e91e0069b65:~/src$ python manage.py dumpdata --indent 2 --all --natural-primary --natural-foreign --traceback
[…]
{
  "model": "pretixbase.globalsettingsobject_settingsstore",
  "pk": 27,
  "fields": {
    "key": "payment_stripe_connect_test_publishable_key",
    "value": ""
  }
}Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 902, in get_queryset
    return self.instance._prefetched_objects_cache[self.prefetch_cache_name]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CheckinList' object has no attribute '_prefetched_objects_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pretix/src/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/dumpdata.py", line 232, in handle
    serializers.serialize(
  File "/usr/local/lib/python3.11/site-packages/django/core/serializers/__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "/usr/local/lib/python3.11/site-packages/django/core/serializers/base.py", line 114, in serialize
    self.handle_m2m_field(obj, field)
  File "/usr/local/lib/python3.11/site-packages/django/core/serializers/python.py", line 72, in handle_m2m_field
    getattr(obj, field.name).iterator(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 905, in get_queryset
    return self._apply_rel_filters(queryset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 892, in _apply_rel_filters
    return queryset._next_is_sticky().filter(**self.core_filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_scopes/manager.py", line 14, in error
    raise ScopeError("A scope on dimension(s) {} needs to be active for this query.".format(
django_scopes.exceptions.ScopeError: A scope on dimension(s) organizer needs to be active for this query.

```

### Steps to reproduce

Run python manage.py dumpdata. It doesn’t work for me, neither on the live instance (using the pretix Docker container), nor in the dev setup.

**Comment by raphaelm** [comment]
Unfortunately, I don't think there's an easy way to make dumpdata work with django-scopes :( And as far as I remember, dumpdata didn't work for pretix even before we used django-scopes, for a reason I can't remember. I have long stopped using dumpdata/loaddata for most cases because it performs poorly for large data sets. For sqlite->postgres one could use pgloader, but I'm sure there are tools out there for the other way 'round as well. (Or just fire up psql in docker :))

**Comment by stapelberg** [comment]
Thanks for letting me know!

Regarding running Postgres in Docker: sure, I can do that. What’s the easiest way to point a local dev setup to said Postgres instance, though? Currently, I’m making a bunch of changes in src/pretix/settings.py. Should I just use a modified version of my live pretix.cfg somehow, or are there magic environment variables I didn’t see? Or is modifying settings.py the recommended way after all?

**Comment by raphaelm** [comment]
No, the recommended way would be to drop a pretix.cfg in your working directory. It can include just the database block

**Comment by stapelberg** [comment]
Ah, thanks for spelling it out. I stripped down pretix.cfg to only contain the database block and that worked :)

I’ll close this ticket as I get the impression that chances are pretty slim that we can get dumpdata to work.
