### ISSUE TITLE
Problem updating requirements

### ISSUE THREAD

**Issue by ligi** [pretix/pretix#318]
After I pulled the latest master I got the following error:

```
⋊> ~/g/3/p/src on master ⨯ python3 manage.py runserver                                                                                12:24:34
^[[AUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f9815412378>
Traceback (most recent call last):
  File "/home/ligi/.local/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/ligi/.local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/ligi/.local/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/ligi/.local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ligi/.local/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/ligi/.local/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ligi/.local/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ligi/.local/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'statici18n'
```

so I thought - just a new dependency and I have to install them - but now updating the requirements fails for me:

```
⋊> ~/g/3/p/src on master ⨯ pip install -r requirements.txt -r requirements/dev.txt 

Collecting Django<1.11,>=1.10 (from -r requirements/production.txt (line 2))
  Using cached Django-1.10.3-py2.py3-none-any.whl
Collecting python-dateutil (from -r requirements/production.txt (line 3))
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting pytz (from -r requirements/production.txt (line 4))
  Using cached pytz-2016.7-py2.py3-none-any.whl
Collecting django-bootstrap3<7.2,>=7.1 (from -r requirements/production.txt (line 5))
Collecting django-formset-js from git+https://github.com/pretix/django-formset-js.git@master#egg=django-formset-js (from -r requirements/production.txt (line 6))
  Cloning https://github.com/pretix/django-formset-js.git (to master) to /tmp/pip-build-KEpPWS/django-formset-js
Collecting django-compressor==2.1 (from -r requirements/production.txt (line 7))
  Using cached django_compressor-2.1-py2.py3-none-any.whl
Collecting reportlab<3.3,>=3.2 (from -r requirements/production.txt (line 8))
Collecting PyPDF2 from git+https://github.com/pretix/PyPDF2.git@pretix#egg=PyPDF2 (from -r requirements/production.txt (line 9))
  Cloning https://github.com/pretix/PyPDF2.git (to pretix) to /tmp/pip-build-KEpPWS/PyPDF2
Collecting easy-thumbnails<3,>=2.2 (from -r requirements/production.txt (line 10))
  Using cached easy_thumbnails-2.3-py2.py3-none-any.whl
Collecting django-libsass (from -r requirements/production.txt (line 11))
Collecting libsass (from -r requirements/production.txt (line 12))
  Using cached libsass-0.11.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting django-otp==0.3.* (from -r requirements/production.txt (line 13))
  Using cached django_otp-0.3.7-py2.py3-none-any.whl
Collecting python-u2flib-server==4.* (from -r requirements/production.txt (line 14))
Collecting celery from git+https://github.com/pretix/celery.git@pretix#egg=celery (from -r requirements/production.txt (line 18))
  Cloning https://github.com/pretix/celery.git (to pretix) to /tmp/pip-build-KEpPWS/celery
Collecting django-statici18n==1.2.* (from -r requirements/production.txt (line 19))
  Downloading django_statici18n-1.2.1-py2.py3-none-any.whl
Collecting BeautifulSoup4 (from -r requirements/production.txt (line 22))
  Using cached beautifulsoup4-4.5.1-py2-none-any.whl
Collecting html5lib (from -r requirements/production.txt (line 23))
  Using cached html5lib-0.999999999-py2.py3-none-any.whl
Collecting slimit (from -r requirements/production.txt (line 24))
Collecting lxml (from -r requirements/production.txt (line 25))
  Using cached lxml-3.6.4-cp27-cp27mu-manylinux1_x86_64.whl
Collecting static3==0.6.1 (from -r requirements/production.txt (line 26))
Collecting dj-static (from -r requirements/production.txt (line 27))
Collecting csscompressor (from -r requirements/production.txt (line 28))
Collecting django-markup (from -r requirements/production.txt (line 29))
Collecting markdown (from -r requirements/production.txt (line 30))
Collecting paypalrestsdk<1.10,<2.0,>=1.9 (from -r requirements/paypal.txt (line 1))
Collecting pycparser==2.13 (from -r requirements/paypal.txt (line 2))
Collecting stripe<1.23,>=1.22 (from -r requirements/stripe.txt (line 1))
Collecting chardet<3,>=2.3 (from -r requirements/banktransfer.txt (line 1))
Collecting mt-940==3.2 (from -r requirements/banktransfer.txt (line 2))
Collecting django-debug-toolbar==1.5 (from -r requirements/dev.txt (line 1))
  Using cached django_debug_toolbar-1.5-py2.py3-none-any.whl
Collecting sqlparse==0.2.1 (from -r requirements/dev.txt (line 2))
  Using cached sqlparse-0.2.1-py2.py3-none-any.whl
Collecting pep8==1.5.7 (from -r requirements/dev.txt (line 4))
  Using cached pep8-1.5.7-py2.py3-none-any.whl
Collecting pyflakes==1.1.0 (from -r requirements/dev.txt (line 5))
  Using cached pyflakes-1.1.0-py2.py3-none-any.whl
Collecting pep8-naming (from -r requirements/dev.txt (line 6))
  Using cached pep8_naming-0.4.1-py2.py3-none-any.whl
Collecting flake8 (from -r requirements/dev.txt (line 7))
  Using cached flake8-3.0.4-py2.py3-none-any.whl
Collecting coveralls (from -r requirements/dev.txt (line 8))
  Using cached coveralls-1.1-py2.py3-none-any.whl
Collecting coverage (from -r requirements/dev.txt (line 9))
Collecting pytest==2.9.* (from -r requirements/dev.txt (line 10))
  Using cached pytest-2.9.2-py2.py3-none-any.whl
Collecting pytest-django (from -r requirements/dev.txt (line 11))
  Using cached pytest_django-3.0.0-py2.py3-none-any.whl
Collecting isort (from -r requirements/dev.txt (line 12))
  Using cached isort-4.2.5-py2.py3-none-any.whl
Collecting pytest-mock (from -r requirements/dev.txt (line 13))
  Downloading pytest_mock-1.4.0-py2.py3-none-any.whl
Collecting pytest-rerunfailures (from -r requirements/dev.txt (line 14))
  Using cached pytest_rerunfailures-2.1.0-py2.py3-none-any.whl
Collecting pytest-warnings (from -r requirements/dev.txt (line 15))
Collecting six>=1.5 (from python-dateutil->-r requirements/production.txt (line 3))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting django-jquery-js (from django-formset-js->-r requirements/production.txt (line 6))
Collecting django-appconf>=1.0 (from django-compressor==2.1->-r requirements/production.txt (line 7))
  Using cached django_appconf-1.0.2-py2.py3-none-any.whl
Collecting rjsmin==1.0.12 (from django-compressor==2.1->-r requirements/production.txt (line 7))
Collecting rcssmin==1.0.6 (from django-compressor==2.1->-r requirements/production.txt (line 7))
Collecting pillow>=2.4.0 (from reportlab<3.3,>=3.2->-r requirements/production.txt (line 8))
  Using cached Pillow-3.4.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pip>=1.4.1 (from reportlab<3.3,>=3.2->-r requirements/production.txt (line 8))
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 402kB/s 
Collecting setuptools>=2.2 (from reportlab<3.3,>=3.2->-r requirements/production.txt (line 8))
  Downloading setuptools-28.8.0-py2.py3-none-any.whl (472kB)
    100% |████████████████████████████████| 481kB 633kB/s 
Collecting cryptography>=1.2 (from python-u2flib-server==4.*->-r requirements/production.txt (line 14))
  Downloading cryptography-1.5.3.tar.gz (400kB)
    100% |████████████████████████████████| 409kB 637kB/s 
Collecting enum34 (from python-u2flib-server==4.*->-r requirements/production.txt (line 14))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting billiard<3.4,>=3.3.0.23 (from celery->-r requirements/production.txt (line 18))
Collecting kombu<3.1,>=3.0.34 (from celery->-r requirements/production.txt (line 18))
  Using cached kombu-3.0.37-py2.py3-none-any.whl
Collecting webencodings (from html5lib->-r requirements/production.txt (line 23))
Collecting ply>=3.4 (from slimit->-r requirements/production.txt (line 24))
Collecting requests>=1.0.0 (from paypalrestsdk<1.10,<2.0,>=1.9->-r requirements/paypal.txt (line 1))
  Using cached requests-2.11.1-py2.py3-none-any.whl
Collecting pyopenssl>=0.14 (from paypalrestsdk<1.10,<2.0,>=1.9->-r requirements/paypal.txt (line 1))
  Using cached pyOpenSSL-16.2.0-py2.py3-none-any.whl
Collecting pyyaml (from mt-940==3.2->-r requirements/banktransfer.txt (line 2))
Collecting configparser; python_version < "3.2" (from flake8->-r requirements/dev.txt (line 7))
Collecting mccabe<0.6.0,>=0.5.0 (from flake8->-r requirements/dev.txt (line 7))
  Using cached mccabe-0.5.2-py2.py3-none-any.whl
Collecting pycodestyle<2.1.0,>=2.0.0 (from flake8->-r requirements/dev.txt (line 7))
  Using cached pycodestyle-2.0.0-py2.py3-none-any.whl
Collecting docopt>=0.6.1 (from coveralls->-r requirements/dev.txt (line 8))
Collecting py>=1.4.29 (from pytest==2.9.*->-r requirements/dev.txt (line 10))
  Using cached py-1.4.31-py2.py3-none-any.whl
Collecting mock; python_version == "2.6" or python_version == "2.7" (from pytest-mock->-r requirements/dev.txt (line 13))
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting idna>=2.0 (from cryptography>=1.2->python-u2flib-server==4.*->-r requirements/production.txt (line 14))
  Using cached idna-2.1-py2.py3-none-any.whl
Collecting pyasn1>=0.1.8 (from cryptography>=1.2->python-u2flib-server==4.*->-r requirements/production.txt (line 14))
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting ipaddress (from cryptography>=1.2->python-u2flib-server==4.*->-r requirements/production.txt (line 14))
  Using cached ipaddress-1.0.17-py2-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=1.2->python-u2flib-server==4.*->-r requirements/production.txt (line 14))
  Downloading cffi-1.9.1.tar.gz (407kB)
    100% |████████████████████████████████| 409kB 826kB/s 
Collecting anyjson>=0.3.3 (from kombu<3.1,>=3.0.34->celery->-r requirements/production.txt (line 18))
Collecting amqp<2.0,>=1.4.9 (from kombu<3.1,>=3.0.34->celery->-r requirements/production.txt (line 18))
  Using cached amqp-1.4.9-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock; python_version == "2.6" or python_version == "2.7"->pytest-mock->-r requirements/dev.txt (line 13))
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock; python_version == "2.6" or python_version == "2.7"->pytest-mock->-r requirements/dev.txt (line 13))
  Using cached pbr-1.10.0-py2.py3-none-any.whl
Building wheels for collected packages: cryptography, cffi
  Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KEpPWS/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpUz5Otbpip-wheel- --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-KEpPWS/cryptography/setup.py", line 334, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 351, in __init__
      _Distribution.__init__(self, attrs)
    File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
      self.finalize_options()
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 408, in finalize_options
      ep.load()(self, ep.name, value)
    File "/home/ligi/.local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 181, in cffi_modules
      add_cffi_module(dist, cffi_module)
    File "/home/ligi/.local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 48, in add_cffi_module
      execfile(build_file_name, mod_vars)
    File "/home/ligi/.local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 24, in execfile
      exec(code, glob, glob)
    File "src/_cffi_src/build_openssl.py", line 81, in <module>
      extra_link_args=extra_link_args(compiler_type()),
    File "/tmp/pip-build-KEpPWS/cryptography/src/_cffi_src/utils.py", line 61, in build_ffi_for_binding
      extra_link_args=extra_link_args,
    File "/tmp/pip-build-KEpPWS/cryptography/src/_cffi_src/utils.py", line 69, in build_ffi
      ffi = FFI()
    File "/home/ligi/.local/lib/python2.7/site-packages/cffi/api.py", line 59, in __init__
      "version mismatch, %s != %s" % (backend.__version__, __version__)
  AssertionError: version mismatch, 1.7.0 != 1.8.3
  
  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KEpPWS/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-KEpPWS/cryptography/setup.py", line 334, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 351, in __init__
      _Distribution.__init__(self, attrs)
    File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
      self.finalize_options()
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 408, in finalize_options
      ep.load()(self, ep.name, value)
    File "/home/ligi/.local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 181, in cffi_modules
      add_cffi_module(dist, cffi_module)
    File "/home/ligi/.local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 48, in add_cffi_module
      execfile(build_file_name, mod_vars)
    File "/home/ligi/.local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 24, in execfile
      exec(code, glob, glob)
    File "src/_cffi_src/build_openssl.py", line 81, in <module>
      extra_link_args=extra_link_args(compiler_type()),
    File "/tmp/pip-build-KEpPWS/cryptography/src/_cffi_src/utils.py", line 61, in build_ffi_for_binding
      extra_link_args=extra_link_args,
    File "/tmp/pip-build-KEpPWS/cryptography/src/_cffi_src/utils.py", line 69, in build_ffi
      ffi = FFI()
    File "/home/ligi/.local/lib/python2.7/site-packages/cffi/api.py", line 59, in __init__
      "version mismatch, %s != %s" % (backend.__version__, __version__)
  AssertionError: version mismatch, 1.7.0 != 1.8.3
  
  ----------------------------------------
  Failed cleaning build dir for cryptography
  Running setup.py bdist_wheel for cffi ... done
  Stored in directory: /home/ligi/.cache/pip/wheels/65/1e/6d/ee5dbc0573d081dfe8bfc216fbe56b60bf16c93e0a1e6429f0
Successfully built cffi
Failed to build cryptography
Installing collected packages: Django, six, python-dateutil, pytz, django-bootstrap3, django-jquery-js, django-formset-js, django-appconf, rjsmin, rcssmin, django-compressor, pillow, pip, setuptools, reportlab, PyPDF2, easy-thumbnails, libsass, django-libsass, django-otp, idna, pyasn1, enum34, ipaddress, pycparser, cffi, cryptography, python-u2flib-server, billiard, anyjson, amqp, kombu, celery, django-statici18n, BeautifulSoup4, webencodings, html5lib, ply, slimit, lxml, static3, dj-static, csscompressor, django-markup, markdown, requests, pyopenssl, paypalrestsdk, stripe, chardet, pyyaml, mt-940, sqlparse, django-debug-toolbar, pep8, pyflakes, pep8-naming, configparser, mccabe, pycodestyle, flake8, docopt, coverage, coveralls, py, pytest, pytest-django, isort, funcsigs, pbr, mock, pytest-mock, pytest-rerunfailures, pytest-warnings
  Running setup.py install for django-formset-js ... done
  Running setup.py install for PyPDF2 ... done
  Running setup.py install for cryptography ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KEpPWS/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JWjW7g-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-KEpPWS/cryptography/setup.py", line 334, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 351, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 408, in finalize_options
        ep.load()(self, ep.name, value)
      File "/home/ligi/.local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 187, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/home/ligi/.local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/home/ligi/.local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/_cffi_src/build_openssl.py", line 81, in <module>
        extra_link_args=extra_link_args(compiler_type()),
      File "/tmp/pip-build-KEpPWS/cryptography/src/_cffi_src/utils.py", line 61, in build_ffi_for_binding
        extra_link_args=extra_link_args,
      File "/tmp/pip-build-KEpPWS/cryptography/src/_cffi_src/utils.py", line 69, in build_ffi
        ffi = FFI()
      File "/home/ligi/.local/lib/python2.7/site-packages/cffi/api.py", line 59, in __init__
        "version mismatch, %s != %s" % (backend.__version__, __version__)
    AssertionError: version mismatch, 1.7.0 != 1.9.1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KEpPWS/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JWjW7g-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-KEpPWS/cryptography/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by raphaelm** [comment]
Can you try if ``pip install -Ur requirements.txt -r requirements/dev.txt`` helps so ``cffi`` gets upgraded?

**Comment by ligi** [comment]
just found out that my problem is that I used pip and not pip3 - was just confused as the documentation states pip and not pip3 - might have been my inexperience with python here

**Comment by raphaelm** [comment]
Using a virtualenvironment *should* alias pip to pip3, but apparently it doesn't in all cases. Let's keep this as a docs issue then. :)

**Comment by ligi** [comment]
thanks!
