### ISSUE TITLE
Cannot export invoicedata

### ISSUE THREAD

**Issue by rp3r** [pretix/pretix#3207]
### Problem and impact

If trying to export all invocedata (multiple events) as excel an internal error occurs.

After updating to v4.18 the problem was gone but since today we have it back again.
Exporting as CSV works well though.

Anyone else had this issue?

As it seems the worker will be killed prematurely
Log output:
```bash
[2023-04-04 14:31:59,039: ERROR/MainProcess] Process 'ForkPoolWorker-36' pid:784 exited with 'signal 9 (SIGKILL)'
[2023-04-04 14:31:59,057: WARNING/MainProcess] --- Logging error ---
[2023-04-04 14:31:59,058: WARNING/MainProcess] Traceback (most recent call last):
[2023-04-04 14:31:59,059: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
    raise WorkerLostError(
[2023-04-04 14:31:59,059: WARNING/MainProcess] billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 245.
[2023-04-04 14:31:59,059: WARNING/MainProcess]
During handling of the above exception, another exception occurred:
[2023-04-04 14:31:59,060: WARNING/MainProcess] Traceback (most recent call last):
[2023-04-04 14:31:59,061: WARNING/MainProcess]   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2023-04-04 14:31:59,062: WARNING/MainProcess]   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2023-04-04 14:31:59,062: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/utils/log.py", line 146, in format
    msg = super().format(record)
          ^^^^^^^^^^^^^^^^^^^^^^
[2023-04-04 14:31:59,063: WARNING/MainProcess]   File "/usr/local/lib/python3.11/logging/__init__.py", line 695, in format
    record.exc_text = self.formatException(record.exc_info)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-04-04 14:31:59,063: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/utils/log.py", line 142, in formatException
    r = super().formatException(ei)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-04-04 14:31:59,064: WARNING/MainProcess]   File "/usr/local/lib/python3.11/logging/__init__.py", line 645, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
[2023-04-04 14:31:59,064: WARNING/MainProcess]   File "/usr/local/lib/python3.11/traceback.py", line 124, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-04-04 14:31:59,065: WARNING/MainProcess]   File "/usr/local/lib/python3.11/traceback.py", line 690, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-04-04 14:31:59,065: WARNING/MainProcess]   File "/usr/local/lib/python3.11/traceback.py", line 416, in _extract_from_extended_frame_gen
    for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
[2023-04-04 14:31:59,065: WARNING/MainProcess]   File "/usr/local/lib/python3.11/traceback.py", line 353, in _walk_tb_with_full_positions
    positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-04-04 14:31:59,066: WARNING/MainProcess]   File "/usr/local/lib/python3.11/traceback.py", line 366, in _get_code_position
    positions_gen = code.co_positions()
                    ^^^^^^^^^^^^^^^^^
[2023-04-04 14:31:59,066: WARNING/MainProcess] AttributeError: '_Code' object has no attribute 'co_positions'
[2023-04-04 14:31:59,067: WARNING/MainProcess] Call stack:
[2023-04-04 14:31:59,068: WARNING/MainProcess]   File "/usr/local/bin/celery", line 33, in <module>
    sys.exit(load_entry_point('celery==5.2.7', 'console_scripts', 'celery')())
[2023-04-04 14:31:59,069: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
[2023-04-04 14:31:59,069: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
[2023-04-04 14:31:59,070: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
[2023-04-04 14:31:59,070: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
[2023-04-04 14:31:59,070: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-04-04 14:31:59,071: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-04-04 14:31:59,071: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
[2023-04-04 14:31:59,071: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-04-04 14:31:59,072: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-04-04 14:31:59,072: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 351, in worker
    worker.start()
[2023-04-04 14:31:59,073: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2023-04-04 14:31:59,073: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-04-04 14:31:59,073: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-04-04 14:31:59,074: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
[2023-04-04 14:31:59,074: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-04-04 14:31:59,075: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 628, in start
    c.loop(*c.loop_args())
[2023-04-04 14:31:59,075: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
[2023-04-04 14:31:59,075: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/hub.py", line 301, in create_loop
    poll_timeout = fire_timers(propagate=propagate) if scheduled else 1
[2023-04-04 14:31:59,076: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/hub.py", line 143, in fire_timers
    entry()
[2023-04-04 14:31:59,077: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/timer.py", line 64, in __call__
    return self.fun(*self.args, **self.kwargs)
[2023-04-04 14:31:59,077: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/timer.py", line 126, in _reschedules
    return fun(*args, **kwargs)
[2023-04-04 14:31:59,078: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1351, in maintain_pool
    self._maintain_pool()
[2023-04-04 14:31:59,078: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1342, in _maintain_pool
    joined = self._join_exited_workers()
[2023-04-04 14:31:59,079: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1229, in _join_exited_workers
    self.on_job_process_lost(
[2023-04-04 14:31:59,080: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/asynpool.py", line 1139, in on_job_process_lost
    self.mark_as_worker_lost(job, exitcode)
[2023-04-04 14:31:59,080: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1270, in mark_as_worker_lost
    job._set(None, (False, ExceptionInfo()))
[2023-04-04 14:31:59,081: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1828, in _set
    self.safe_apply_callback(
[2023-04-04 14:31:59,081: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 1796, in safe_apply_callback
    fun(*args, **kwargs)
[2023-04-04 14:31:59,082: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/worker/request.py", line 596, in on_failure
    error('Task handler raised error: %r', exc,
[2023-04-04 14:31:59,082: WARNING/MainProcess]   File "/usr/local/lib/python3.11/logging/__init__.py", line 1518, in error
    self._log(ERROR, msg, args, **kwargs)
[2023-04-04 14:31:59,082: WARNING/MainProcess]   File "/usr/local/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
[2023-04-04 14:31:59,083: WARNING/MainProcess]   File "/usr/local/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
[2023-04-04 14:31:59,083: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/logging.py", line 96, in sentry_patched_callhandlers
    return old_callhandlers(self, record)
[2023-04-04 14:31:59,084: WARNING/MainProcess] Message: 'Task handler raised error: %r'
Arguments: (WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 245.'),)
ERROR 2023-04-04 14:31:59,401 pretix.base.tasks tasks Unexpected exception: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 245.')
ERROR 2023-04-04 14:31:59,402 pretix.base.tasks tasks Unexpected exception: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 245.')
```

### Steps to reproduce

1. have multiple events with invoice data to export
2. go to organizer => Export => Invoice data
3. select as export format "Combined Excel" and all events
4. Start export

### Version

4.18.0

**Comment by raphaelm** [comment]
Could you check if your server happens to run out of memory while trying to create the export?
