### ISSUE TITLE
Error 500 on custom subdomain on Pretix 4.20

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#3371]
### Problem and impact

When trying to reach Pretix on a custom subdomain there is an error 500.

The error in the logs is `ValueError: Missing staticfiles manifest entry for 'jsi18n/de-informal/djangojs.js'`, Traceback below.

We checked that the `rebuild` and `updatestyles` update steps ran successfully. 

<details>
<summary>Traceback</summary>

```
Jun 01 11:15:35 pretix gunicorn[70326]: ERROR 2023-06-01 11:15:35,638 django.request log Internal Server Error: /
Jun 01 11:15:35 pretix gunicorn[70326]: Traceback (most recent call last):
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
Jun 01 11:15:35 pretix gunicorn[70326]:     response = get_response(request)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
Jun 01 11:15:35 pretix gunicorn[70326]:     response = response.render()
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/response.py", line 105, in render
Jun 01 11:15:35 pretix gunicorn[70326]:     self.content = self.rendered_content
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/response.py", line 83, in rendered_content
Jun 01 11:15:35 pretix gunicorn[70326]:     return template.render(context, self._request)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
Jun 01 11:15:35 pretix gunicorn[70326]:     return self.template.render(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/base.py", line 170, in render
Jun 01 11:15:35 pretix gunicorn[70326]:     return self._render(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
Jun 01 11:15:35 pretix gunicorn[70326]:     return self.nodelist.render(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 01 11:15:35 pretix gunicorn[70326]:     bit = node.render_annotated(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 01 11:15:35 pretix gunicorn[70326]:     return self.render(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
Jun 01 11:15:35 pretix gunicorn[70326]:     return compiled_parent._render(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
Jun 01 11:15:35 pretix gunicorn[70326]:     return self.nodelist.render(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 01 11:15:35 pretix gunicorn[70326]:     bit = node.render_annotated(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 01 11:15:35 pretix gunicorn[70326]:     return self.render(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
Jun 01 11:15:35 pretix gunicorn[70326]:     return compiled_parent._render(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
Jun 01 11:15:35 pretix gunicorn[70326]:     return self.nodelist.render(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 01 11:15:35 pretix gunicorn[70326]:     bit = node.render_annotated(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 01 11:15:35 pretix gunicorn[70326]:     return self.render(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 315, in render
Jun 01 11:15:35 pretix gunicorn[70326]:     return nodelist.render(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 01 11:15:35 pretix gunicorn[70326]:     bit = node.render_annotated(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 01 11:15:35 pretix gunicorn[70326]:     return self.render(context)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/template/library.py", line 192, in render
Jun 01 11:15:35 pretix gunicorn[70326]:     output = self.func(*resolved_args, **resolved_kwargs)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/statici18n/templatetags/statici18n.py", line 29, in statici18n
Jun 01 11:15:35 pretix gunicorn[70326]:     return static(get_path(locale))
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/templatetags/static.py", line 167, in static
Jun 01 11:15:35 pretix gunicorn[70326]:     return StaticNode.handle_simple(path)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/templatetags/static.py", line 118, in handle_simple
Jun 01 11:15:35 pretix gunicorn[70326]:     return staticfiles_storage.url(path)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 147, in url
Jun 01 11:15:35 pretix gunicorn[70326]:     return self._url(self.stored_name, name, force)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 126, in _url
Jun 01 11:15:35 pretix gunicorn[70326]:     hashed_name = hashed_name_func(*args)
Jun 01 11:15:35 pretix gunicorn[70326]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 417, in stored_name
Jun 01 11:15:35 pretix gunicorn[70326]:     raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
Jun 01 11:15:35 pretix gunicorn[70326]: ValueError: Missing staticfiles manifest entry for 'jsi18n/de-informal/djangojs.js'
```

</details>

### Expected behaviour

Pretix is reachable on custom subdomains.

### Link

https://tix.kif.rocks

### Operating system, dependency versions

Python 3.10, Ubuntu 22.04 LTS

### Version

4.20

**Comment by raphaelm** [comment]
Weird, I don't see how that could be related to the custom domain. Might it be related to the shop language instead?

**Comment by thegcat** [comment]
> Weird, I don't see how that could be related to the custom domain. Might it be related to the shop language instead?

Short Feedback on this (I had meant to talk to you at GPN about this, sorry): As a user I don't care much where the problem might come from but how to (help) fix it 😁 An actionable thing to try ("try the update again and change the locale from X to Y in event > settings > place Z, does this fix the problem?") would help bring things forward.

**Comment by thegcat** [comment]
Speaking of actionables: We tried the update again today, and it seems 4.20.1 and/or whatever else updates came with the `pip` updates seems to have solved this issue for us.
