### ISSUE TITLE
Error after installing and configuring GeoLite2-Country.mmdb

### ISSUE THREAD

**Issue by Konafets** [pretix/pretix#3391]
### Problem and impact

I copied the `GeoLite2-Country.mmdb` to the webspace and configured it in `pretix.cfg` like this:

```
[geoip]
path=/home/his/
filename_country=GeoLite2-Country.mmdb
```

After restarting Pretix I got an error preventing me to get back to the admin panel (in fact it prevented me to do anything). The log shows this error everytime I access pretix:

```shell
2023-06-06 09:47:44,174 DEBG 'pretix' stderr output:
ERROR 2023-06-06 09:47:44,128 django.request log Internal Server Error: /control/
Traceback (most recent call last):
  File "/home/his/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/his/.local/lib/python3.11/site-packages/pretix/control/middleware.py", line 129, in __call__
    assert_session_valid(request)
  File "/home/his/.local/lib/python3.11/site-packages/pretix/helpers/security.py", line 77, in assert_session_valid
    country = cache.get_or_set(f'geoip_country_{hashed_client_ip}', lambda: _get_country(request), timeout=300)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/his/.local/lib/python3.11/site-packages/pretix/helpers/cache.py", line 29, in get_or_set
    default = default()
              ^^^^^^^^^
  File "/home/his/.local/lib/python3.11/site-packages/pretix/helpers/security.py", line 77, in <lambda>
    country = cache.get_or_set(f'geoip_country_{hashed_client_ip}', lambda: _get_country(request), timeout=300)
                                                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/his/.local/lib/python3.11/site-packages/pretix/helpers/security.py", line 53, in _get_country
    res = _geoip.country(get_client_ip(request))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/his/.local/lib/python3.11/site-packages/django/contrib/gis/geoip2/base.py", line 191, in country
    return Country(self._country_or_city(enc_query))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/his/.local/lib/python3.11/site-packages/geoip2/database.py", line 139, in country
    Country, self._model_for(geoip2.models.Country, "Country", ip_address)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/his/.local/lib/python3.11/site-packages/geoip2/database.py", line 253, in _model_for
    (record, prefix_len) = self._get(types, ip_address)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/his/.local/lib/python3.11/site-packages/geoip2/database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 100.64.242.1 is not in the database.
```

I am not really sure where the IP 100.64.242.1 comes from. Its neither mine nor the one from the server.

### Browser (software, desktop or mobile?) and version

Chrome

### Operating system, dependency versions

Linux

### Version

4.20

**Comment by raphaelm** [comment]
Interesting. We use a different database. I did not know it would fail this badly, I think we should just ignore IPs not in the DB
