### ISSUE TITLE
ResolutionTooDeep Exception when installing pip dependencies for Development setup

### ISSUE THREAD

**Issue by carl-egge** [pretix/pretix#3428]
### Problem and impact

When trying to install the Development setup to work with the code I get an Exception during the execution of the command:
`pip3 install -e ".[dev]"`

I was following the Development setup in the [docs](https://docs.pretix.eu/en/latest/development/setup.html#devsetup), and when running the above the installation was taking a long long time and final through the following Error:

```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/<path-to-env>/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/<path-to-env>/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/<path-to-env>/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/<path-to-env>/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/<path-to-env>/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/<path-to-env>/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
```

This happened to me with different pip packages. I also tried to run the command on the master and on the latest release branch (pretix 4.20.0). I tried to install the causing packages manually and reran the command but got the same Exception.

### Expected behaviour

I would expect that pip can install all the dependencies.

### Steps to reproduce

See the [docs](https://docs.pretix.eu/en/latest/development/setup.html#working-with-the-code)

Follow the steps in the Development setup and run the following command in a fresh python virtual env:
`pip3 install -e ".[dev]"`

### Screenshots

See the Code Exception above.

### Operating system, dependency versions

Ubuntu 20.04.6 LTS (focal) with python version 3.8.10

### Version

4.20.x

**Comment by raphaelm** [comment]
Not sure if it's the cause of this but might be: We require python 3.9+

**Comment by carl-egge** [comment]
Yes!! This fixed the problem.

I need to run it with python3.9+ and then everything worked fine!

Thank you for the help!
