### ISSUE TITLE
Upgrade error from 4.6 to 4.10 (and above)

### ISSUE THREAD

**Issue by m-sternberg** [pretix/pretix#3712]
### Problem and impact

We try to upgrade from pretix/standalone:4.6 to newer versions. Upgrade to 4.9 works but any version beyond fails. We're aware of the db migration to PostgreSQL in later versions. We still run Mariadb as our db backend but even an upgrade to 4.10 fails with the below exception:

```
pretixuser@e82c5b018669:/$ pretix upgrade                                                                                      
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code                                                         
    exec(code, run_globals)
  File "/pretix/src/pretix/__main__.py", line 30, in <module>                                                                  
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/managemenfromt/__init__.py", line 419, in execute_from_command_line
    utility.execute()                     
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)                    
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)                                                                                     
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)                                                                                         
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])                                                                                           
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(                                                                                            
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)           
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()        
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module                     
    return _bootstrap._gcd_import(name[level:], package, level)                
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                                     
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load        
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked                     
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked         
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module                   
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/pretix/src/pretix/multidomain/maindomain_urlconf.py", line 45, in <module>
    from pretix.urls import common_patterns
  File "/pretix/src/pretix/urls.py", line 59, in <module>
    re_path(r'^api/v1/', include(('pretix.api.urls', 'pretixapi'), namespace='api-v1')),
  File "/usr/local/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level) 
  File "/pretix/src/pretix/api/urls.py", line 43, in <module>
    from .views import (
  File "/pretix/src/pretix/api/views/exporters.py", line 35, in <module>
    from pretix.api.serializers.exporters import (
  File "/pretix/src/pretix/api/serializers/exporters.py", line 52, in <module>
    (forms.NullBooleanField, serializers.NullBooleanField, ()), 
AttributeError: module 'rest_framework.serializers' has no attribute 'NullBooleanField'
```
No Update later than 4.9 works. What can we do?

### Steps to reproduce

1. Change image tag in yaml from pretix/standalone:4.9 to pretix/standalone:4.10
2. docker stack deploy -c pretix.yaml pretix
3. Set envvar `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` 
3.a) we ran into TypeError: Descriptors cannot not be created directly and this envvar was recommended in the logs:
```
bkf_pretix.1.mb2xlhj4elau@bkf-01    | TypeError: Descriptors cannot not be created directly.                                                                                                                                                                  
bkf_pretix.1.mb2xlhj4elau@bkf-01    | If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.                                                                                                
bkf_pretix.1.mb2xlhj4elau@bkf-01    | If you cannot immediately regenerate your protos, some other possible workarounds are:                                                                                                                                  
bkf_pretix.1.mb2xlhj4elau@bkf-01    |  1. Downgrade the protobuf package to 3.20.x or lower.                                                                                                                                                                  
bkf_pretix.1.mb2xlhj4elau@bkf-01    |  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
5. Run `pretix upgrade` inside container

### Operating system, dependency versions

Debian 10, Docker Swarm 19.03.15

### Version

Community 4.9

**Comment by m-sternberg** [comment]
Thanks for your quick response, but this didn't work either :( Same error. Any ideas? Shall we set debug level? Or in general, is this the way to upgrade pretix: 

- pull newer images and run pretix upgrade manually?

Just asking because I saw auto migrating, which can be disabled as docker envvar.

**Comment by raphaelm** [comment]
> EDIT: Going to the UI under /control/global/update/ - we still see Version 4.6 but we run docker image 4.9 already.

Are you sure you are running 4.9? That does not sound really plausible, and if you were still somehow running 4.6 that would somehow explain the issue.

> Just asking because I saw auto migration, which can be disabled as docker envvar. I assume it's active by default and there is no need to run 'python upgrade'?

Yes.

In theory, nothing should stop you from jumping all the way to 4.20.0 in one go, if that proves to be more successful.

**Comment by m-sternberg** [comment]
Thanks for your reply @raphaelm! We reviewed our infrastructure again and it turned out, Pretix was deployed with a declared volume for /pretix/src. So in this case of course every update didn't work as we were running still version 4.6 the whole time. 

We fixed this now and the update worked. Thanks again for supporting us and thumbs up for this wonderful piece of software!

Best, M
