### ISSUE TITLE
Order position ticket download: can return 500 instead of 409 Conflict

### ISSUE THREAD

**Issue by stapelberg** [pretix/pretix#4229]
### Problem and impact

I recently created a custom signup form for an event that creates a pretix order via the API.

Because I also need to send a custom email confirmation, I don’t use pretix’s mail functionality, but download the ticket PDF via the API and attach it to my own email.

While this works fine usually, I noticed a small number of requests failing with this 500 Internal Server Error:

```
Jun 14 22:49:37 docker[715537]: INFO 2024-06-14 20:49:37,350 pretix.api.exception exception API Exception [409]: "The requested resource is not ready, please retry later."
Jun 14 22:49:37 docker[715537]: WARNING 2024-06-14 20:49:37,361 django.request log Conflict: /api/v1/organizers/vli/events/111/orderpositions/4303/download/pdf/
Jun 14 22:49:37 docker[715537]: WARNING 2024-06-14 20:49:37,361 django.request log Conflict: /api/v1/organizers/vli/events/111/orderpositions/4303/download/pdf/
Jun 14 22:49:37 docker[715537]: [2024-06-14 20:49:37,437: INFO/ForkPoolWorker-1] Task pretix.base.services.tickets.generate[0776f910-21e9-43b5-9884-054ed3c354dd] succeeded in 0.343536717351526s: 60
Jun 14 22:49:37 docker[715537]: [2024-06-14 20:49:37,653: INFO/ForkPoolWorker-2] Task pretix.base.services.tickets.generate[c7465d1d-e54b-4546-b3bc-48ad57f5c8c7] succeeded in 0.3053316450677812s: 61
Jun 14 22:49:37 docker[715537]: ERROR 2024-06-14 20:49:37,697 django.request log Internal Server Error: /api/v1/organizers/vli/events/111/orderpositions/4303/download/pdf/
Jun 14 22:49:37 docker[715537]: Traceback (most recent call last):
Jun 14 22:49:37 docker[715537]:   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
Jun 14 22:49:37 docker[715537]:     response = get_response(request)
Jun 14 22:49:37 docker[715537]:                ^^^^^^^^^^^^^^^^^^^^^
Jun 14 22:49:37 docker[715537]:   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
Jun 14 22:49:37 docker[715537]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jun 14 22:49:37 docker[715537]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 22:49:37 docker[715537]:   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
Jun 14 22:49:37 docker[715537]:     return view_func(*args, **kwargs)
Jun 14 22:49:37 docker[715537]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 22:49:37 docker[715537]:   File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 124, in view
Jun 14 22:49:37 docker[715537]:     return self.dispatch(request, *args, **kwargs)
Jun 14 22:49:37 docker[715537]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 22:49:37 docker[715537]:   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
Jun 14 22:49:37 docker[715537]:     response = self.handle_exception(exc)
Jun 14 22:49:37 docker[715537]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 22:49:37 docker[715537]:   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
Jun 14 22:49:37 docker[715537]:     self.raise_uncaught_exception(exc)
Jun 14 22:49:37 docker[715537]:   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
Jun 14 22:49:37 docker[715537]:     raise exc
Jun 14 22:49:37 docker[715537]:   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
Jun 14 22:49:37 docker[715537]:     response = handler(request, *args, **kwargs)
Jun 14 22:49:37 docker[715537]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 22:49:37 docker[715537]:   File "/pretix/src/pretix/api/views/order.py", line 1302, in download
Jun 14 22:49:37 docker[715537]:     resp = FileResponse(ct.file.file, content_type=ct.type)
Jun 14 22:49:37 docker[715537]:                         ^^^^^^^^^^^^
Jun 14 22:49:37 docker[715537]:   File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/files.py", line 48, in _get_file
Jun 14 22:49:37 docker[715537]:     self._file = self.storage.open(self.name, "rb")
Jun 14 22:49:37 docker[715537]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 22:49:37 docker[715537]:   File "/usr/local/lib/python3.11/site-packages/django/core/files/storage/base.py", line 22, in open
Jun 14 22:49:37 docker[715537]:     return self._open(name, mode)
Jun 14 22:49:37 docker[715537]:            ^^^^^^^^^^^^^^^^^^^^^^
Jun 14 22:49:37 docker[715537]:   File "/usr/local/lib/python3.11/site-packages/django/core/files/storage/filesystem.py", line 68, in _open
Jun 14 22:49:37 docker[715537]:     return File(open(self.path(name), mode))
Jun 14 22:49:37 docker[715537]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 22:49:37 docker[715537]: FileNotFoundError: [Errno 2] No such file or directory: '/data/media/tickets/vli/111/VNEQS-1-pdf-8Z03wPSyTffKIQ7s.dat'

```

### Expected behaviour

The API is documented at https://docs.pretix.eu/en/latest/api/resources/orders.html#order-position-ticket-download to return:

> [409 Conflict](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10) – The file is not yet ready and will now be prepared. Retry the request after waiting for a few seconds.

…so the 500 Internal Server Error seems like a bug to me.

Looking at the code, I suspect my request arrived after line 56 but before line 58: https://github.com/pretix/pretix/blob/877401d8c05680275fafbea7872d1e9fe1ed71f5/src/pretix/base/services/tickets.py#L44-L59

### Steps to reproduce

Here’s how I call the pretix API from my code:

```go
		result, _, err := pretix.OrdersApi.Createorder(ctx, "vli", "111", req)
		if err != nil {
			return "", fmt.Errorf("Pretix-Fehler: %v", err)
		}

		// Handle 409 HTTP response by retrying with a small backoff.
		// Should the ticket not become ready within 5 seconds,
		// we just send the confirmation mail without a ticket.
		var ticketPDF []byte
		for i := 0; i < 20; i++ {
			var resp *http.Response
			var perr error
			ticketPDF, resp, perr = pretix.OrdersApi.Downloadorderpositionpdf(ctx, "vli", "111", result.Positions[0].Id)
			if perr != nil {
				if resp.StatusCode == http.StatusConflict {
					log.Printf("(pretix not yet ready? retrying)")
					time.Sleep(250 * time.Millisecond)
					continue
				}
				return "", fmt.Errorf("Pretix-Fehler: %v", perr)
			}
		}

```

### Version

2024.5

**Comment by wiffbi** [comment]
Your suggestion is actually quite spot on, although a bit more complicated. Line 56 creates a CachedTicket with file being `None` – the actual download checks only CachedTickets where file_isnull=False [(L1292)](https://github.com/pretix/pretix/blob/877401d8c05680275fafbea7872d1e9fe1ed71f5/src/pretix/api/views/order.py#L1292). So that should not generate a 500 …

What I think maybe happens (I am not sure, as it sound like a super rare edge case, but I did not see anything else): request the downlad => no CachedTicket found, ticket is generated through `generate.apply_async` => 409. You re-request the ticket almost immediately, but this time the CachedTicket is in the database, but with file=None (the actual file is not written to disk yet). => 409 again and `generate.apply_async` is called again. In the meantime, the file from the first request is written to disk and the CachedTicket-object updated in the database. You re-request the ticket-download again, this time CachedTicket with its file-attribute is in the database not being None. Everything is fine, CachedTicket found. Now the download is prepared and the code tries to read the file from disk. But in the meantime, the second `generate.apply_async` kicked in and deleted the CachedTicket, that we just read [(tickets.py#L55)](https://github.com/pretix/pretix/blob/877401d8c05680275fafbea7872d1e9fe1ed71f5/src/pretix/base/services/tickets.py#L55) – if I read the docs correctly, the actual file is deleted before the object in the database [(File.delete)](https://docs.djangoproject.com/en/5.0/ref/files/file/#django.core.files.File.delete).

I am not sure, wether we should either change `generate_orderposition` so it deletes all CachedTickets but the last one after the current CachedTicket is created (currently it deletes them before). Or if we should handle the `FileNotFoundError` in the download more gracefully. Or if we should not call `generate.apply_async` again when there is a CachedTicket with file=null.

**Comment by raphaelm** [comment]
I think we should handle the error better, not mess with the deletion. Deletion is important not to be forgotton for privacy reasons.

**Comment by wiffbi** [comment]
Okay, what do you think would be the right output in this case? Still a 409? Sounds reasonable to me.

**Comment by raphaelm** [comment]
I'm not sure I thought it fully through, but as long as we believe it's situation the system will automatically will recover from, 409 sounds good to me
