### ISSUE TITLE
Fresh pretix installation breaks with Postgres 16

### ISSUE THREAD

**Issue by mikaoelitiana** [pretix/pretix#4621]
### Problem and impact

I have tried to run pretix with https://github.com/ZPascal/pretix-docker-compose (community install guide) which has recently started using Postgres 16. When I run a fresh new installation, an old migration breaks and the server can't boot normally. 

### Expected behaviour

Old migrations should still work on fresh new recent DB

### Steps to reproduce

1. Clone https://github.com/ZPascal/pretix-docker-compose
2. `cd pretix-docker-compose`
3. `docker compose up -d`

### Screenshots

```
pretix_app  |   Applying auth.0011_update_proxy_permissions... OK
pretix_app  |   Applying auth.0012_alter_user_first_name_max_length... OK
pretix_app  | Traceback (most recent call last):
pretix_app  |   File "<frozen runpy>", line 198, in _run_module_as_main
pretix_app  |   File "<frozen runpy>", line 88, in _run_code
pretix_app  |   File "/pretix/src/pretix/__main__.py", line 30, in <module>
pretix_app  |     execute_from_command_line(sys.argv)
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
pretix_app  |     utility.execute()
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
pretix_app  |     self.fetch_command(subcommand).run_from_argv(self.argv)
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
pretix_app  |     self.execute(*args, **cmd_options)
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
pretix_app  |     output = self.handle(*args, **options)
pretix_app  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
pretix_app  |     res = handle_func(*args, **kwargs)
pretix_app  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
pretix_app  |     post_migrate_state = executor.migrate(
pretix_app  |                          ^^^^^^^^^^^^^^^^^
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
pretix_app  |     state = self._migrate_all_forwards(
pretix_app  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
pretix_app  |     state = self.apply_migration(
pretix_app  |             ^^^^^^^^^^^^^^^^^^^^^
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
pretix_app  |     state = migration.apply(state, schema_editor)
pretix_app  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
pretix_app  |     operation.database_forwards(
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
pretix_app  |     self.code(from_state.apps, schema_editor)
pretix_app  |   File "/pretix/src/pretix/base/migrations/0001_squashed_0028_auto_20160816_1242.py", line 28, in initial_user
pretix_app  |     user.password = make_password('admin')
pretix_app  |                     ^^^^^^^^^^^^^^^^^^^^^^
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/hashers.py", line 97, in make_password
pretix_app  |     return hasher.encode(password, salt)
pretix_app  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/hashers.py", line 382, in encode
pretix_app  |     data = argon2.low_level.hash_secret(
pretix_app  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pretix_app  |   File "/usr/local/lib/python3.11/site-packages/argon2/low_level.py", line 115, in hash_secret
pretix_app  |     raise HashingError(error_to_str(rv))
pretix_app  | argon2.exceptions.HashingError: Threading failure
```

**Comment by raphaelm** [comment]
I don't think this is related to PostgreSQL 16. https://github.com/hynek/argon2-cffi/issues/171 suggests you might be low on memory?

**Comment by mikaoelitiana** [comment]
Thanks, I will look into that

**Comment by mikaoelitiana** [comment]
I think I have found the explanation of this issue. `argon` needs 8 cpu thread to run the password hashing but on my VPS, I only have 4 vcpus, so it crashes 

https://github.com/hynek/argon2-cffi/blob/a11241605e512206e5488195b3d5c2d2093ae916/src/argon2/_password_hasher.py#L12 

<img width="945" alt="image" src="https://github.com/user-attachments/assets/5b858925-2d98-456f-9595-d839f8e09ffa">

**Comment by mikaoelitiana** [comment]
So I solved this by updating the Django configuration file `src/production_settings.py` to use BCrypt instead of argon: 
```
from pretix.settings import *

LOGGING['handlers']['mail_admins']['include_html'] = True
STORAGES["staticfiles"]["BACKEND"] = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
PASSWORD_HASHERS = [
    # Note that when updating this, all user passwords will be re-hashed on next login, however,
    # the HistoricPassword model will not be changed automatically. In case a serious issue with a hasher
    # comes to light, dropping the contents of the HistoricPassword table might be the more risk-adequate
    # decision.
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
]
```
I updated my custom Dockerfile to have : 

```
FROM pretix/standalone:stable

USER root

ENV IMAGE_CRON_DIR="/image/cron" \
    IMAGE_CONFIG_DIR="/image/config"

ADD files /image
COPY crontab /tmp/crontab

COPY files/config/production_settings.py /pretix/src/production_settings.py

RUN mv /image/supervisord/crond.conf /etc/supervisord/crond.conf && \
    pip uninstall -y argon2-cffi && \
    pip install crontab django[bcrypt] && chmod 644 $IMAGE_CONFIG_DIR/ssl/*.crt && chmod +x $IMAGE_CRON_DIR/cron.py

USER pretixuser

EXPOSE 443

ENTRYPOINT ["pretix"]
CMD ["all"]
```

**Comment by raphaelm** [comment]
Uh, interesting, I don't really like that still :\
