### ISSUE TITLE
Update via Docker does not work

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#469]
When I try to install the pretix-pages plugin in a docker-installation, it fails. 
Installations of other plugins seem to work without these problems.

```
Step 1/5 : FROM pretix/standalone
 ---> cf7a14c55f53
Step 2/5 : USER root
 ---> Using cache
 ---> 794ae587ee9f
Step 3/5 : RUN pip3 install pretix-pages
 ---> Running in fa02105a9157
Collecting pretix-pages
  Downloading pretix_pages-1.1.3-py3-none-any.whl (155kB)
Installing collected packages: pretix-pages
Successfully installed pretix-pages-1.1.3
 ---> d372558c6b85
Removing intermediate container fa02105a9157
Step 4/5 : USER root
 ---> Running in cb947ac34e04
 ---> 2b9aafcafe4a
Removing intermediate container cb947ac34e04
Step 5/5 : RUN cd /pretix/src && sudo -u pretixuser make production
 ---> Running in 0bfae4a14dbd
./manage.py compilemessages
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python3.4/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/pretix_pages/models.py", line 4, in <module>
    from i18nfield.fields import I18nCharField, I18nTextField
ImportError: No module named 'i18nfield'
Makefile:5: recipe for target 'localecompile' failed
make: *** [localecompile] Error 1
The command '/bin/sh -c cd /pretix/src && sudo -u pretixuser make production' returned a non-zero code: 2
```

**Comment by raphaelm** [comment]
Hi,

which pretix version are you using?

Cheers
Raphael

**Comment by saschafoerster** [comment]
I am using pretix/standalone:stable.

**Comment by raphaelm** [comment]
Can you try ``docker pull pretix/standalone:stable``? It *looks* like you have something before 1.1.0, but we are at 1.2.0 now.

**Comment by raphaelm** [comment]
Very weird. Don't know what's going on here right now, then.

**Comment by saschafoerster** [comment]
For the other plugins it's working fine. If I can help be testing, let me know! :) I will figure out the other plugins first.

**Comment by raphaelm** [comment]
If you go to /control/ and then to "Global settings" on the left, is there an "Update check" link at the top? If not, you're not using 1.2.0.

**Comment by saschafoerster** [comment]
There is no "update check" in my installation visible, so probably I am on 1.2.0. I used the stable-tag in docker though.

**Comment by raphaelm** [comment]
Weird, the stable tag should point to 1.2.0. However, I'm not testing this regularly, as I have no productive installation that uses docker hub.

```
# docker pull pretix/standalone:stable
# systemctl restart pretix.service
# docker exec -it pretix.service pretix upgrade
```

also doesn't make the "Update check" appear?

**Comment by saschafoerster** [comment]
Nope, didn't help. And this time no errors during the installation. Sometimes I needed to reboot.

**Comment by raphaelm** [comment]
If I pull ``stable`` from docker hub, I get 1.2.0. However, I forgot something in my last comment: After ``docker pull``, you also need to recompile your own docker image that includes the plugins. Can you try that?

**Comment by saschafoerster** [comment]
I did do that. :) 
```
systemctl stop pretix.service
cd /home/pretix/
docker build -t bonndigital/pretix .
systemctl start pretix.service
```

**Comment by raphaelm** [comment]
Hm, then I'm out of ideas now.

**Comment by raphaelm** [comment]
``docker build --no-cache -t bonndigital/pretix .`` could be worth a try, though

**Comment by saschafoerster** [comment]
Again: ImportError: No module named 'i18nfield'

Maybe this helps? 

```
docker exec -it pretix.service pretix upgrade
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.10/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: auth, banktransfer, contenttypes, easy_thumbnails, otp_static, otp_totp, pretix_cartshare, pretix_sepadebit, pretixbase, pretixdroid, pretixmultidomain, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

**Comment by raphaelm** [comment]
Hm. ``ImportError: No module named 'i18nfield'`` is because you're still stuck with pretix <1.1. The warning in the upgrade command is not related.

Can you try an explicit ``FROM pretix/standalone:stable`` in your custom dockerfile and then rebuild your docker file, then run ``upgrade``, then restart pretix?

**Comment by saschafoerster** [comment]
Happy easter, we just found the egg! 🐰
