### ISSUE TITLE
SQL Error after upgrade from 1.3.0 to 1.6.0 in orders view

### ISSUE THREAD

**Issue by RincewindWizzard** [pretix/pretix#591]
After upgrading my pretix instance I cannot view my orders for my event in the admin panel.
It fails with following error:

> django.db.utils.OperationalError: (1055, "Expression #22 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pretix.pretixbase_invoiceaddress.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")

with following stack trace:

    django.db.utils.OperationalError: (1055, "Expression #22 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pretix.pretixbase_invoiceaddress.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
    ERROR 2017-08-07 20:18:27,136 django.request exception Internal Server Error: /control/event/partei-hsg/partei-slam/orders/
    Traceback (most recent call last):
      File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
        return self.cursor.execute(query, args)
      File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
        self.errorhandler(self, exc, value)
      File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
        raise errorvalue
      File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
        res = self._query(query)
      File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
        rowcount = self._do_query(q)
      File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
        db.query(q)
      File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 292, in query
        _mysql.connection.query(self, query)
    _mysql_exceptions.OperationalError: (1055, "Expression #22 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pretix.pretixbase_invoiceaddress.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/var/pretix/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
        response = get_response(request)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
        response = self.process_exception_by_middleware(e, request)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
        response = response.render()
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/response.py", line 107, in render
        self.content = self.rendered_content
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/response.py", line 84, in rendered_content
        content = template.render(context, self._request)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
        return self.template.render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 207, in render
        return self._render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
        return self.nodelist.render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
        bit = node.render_annotated(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
        return self.render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
        return compiled_parent._render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
        return self.nodelist.render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
        bit = node.render_annotated(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
        return self.render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
        return compiled_parent._render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
        return self.nodelist.render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
        bit = node.render_annotated(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
        return self.render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
        result = block.nodelist.render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
        bit = node.render_annotated(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
        return self.render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 322, in render
        return nodelist.render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
        bit = node.render_annotated(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
        return self.render(context)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 173, in render
        len_values = len(values)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/query.py", line 232, in __len__
        self._fetch_all()
      File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
        self._result_cache = list(self._iterable_class(self))
      File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
        results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
        raise original_exception
      File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 884, in execute_sql
        cursor.execute(sql, params)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
      File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
        return self.cursor.execute(query, args)
      File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
        self.errorhandler(self, exc, value)
      File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
        raise errorvalue
      File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
        res = self._query(query)
      File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
        rowcount = self._do_query(q)
      File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
        db.query(q)
      File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 292, in query
        _mysql.connection.query(self, query)

The SQL statement which causes the error is this:

    SELECT DISTINCT `pretixbase_order`.`id`, `pretixbase_order`.`code`, `pretixbase_order`.`status`, `pretixbase_order`.`event_id`, `pretixbase_order`.`email`, `pretixbase_order`.`locale`, `pretixbase_order`.`secret`, `pretixbase_order`.`datetime`, `pretixbase_order`.`expires`, `pretixbase_order`.`payment_date`, `pretixbase_order`.`payment_provider`, `pretixbase_order`.`payment_fee`, `pretixbase_order`.`payment_fee_tax_rate`, `pretixbase_order`.`payment_fee_tax_value`, `pretixbase_order`.`payment_info`, `pretixbase_order`.`payment_manual`, `pretixbase_order`.`total`, `pretixbase_order`.`comment`, `pretixbase_order`.`expiry_reminder_sent`, `pretixbase_order`.`meta_info`, COUNT(DISTINCT `pretixbase_orderposition`.`id`) AS `pcnt`, `pretixbase_invoiceaddress`.`id`, `pretixbase_invoiceaddress`.`last_modified`, `pretixbase_invoiceaddress`.`is_business`, `pretixbase_invoiceaddress`.`order_id`, `pretixbase_invoiceaddress`.`company`, `pretixbase_invoiceaddress`.`name`, `pretixbase_invoiceaddress`.`street`, `pretixbase_invoiceaddress`.`zipcode`, `pretixbase_invoiceaddress`.`city`, `pretixbase_invoiceaddress`.`country_old`, `pretixbase_invoiceaddress`.`country`, `pretixbase_invoiceaddress`.`vat_id` FROM `pretixbase_order` LEFT OUTER JOIN `pretixbase_orderposition` ON (`pretixbase_order`.`id` = `pretixbase_orderposition`.`order_id`) LEFT OUTER JOIN `pretixbase_invoiceaddress` ON (`pretixbase_order`.`id` = `pretixbase_invoiceaddress`.`order_id`) WHERE `pretixbase_order`.`event_id` = 4 GROUP BY `pretixbase_order`.`id` ORDER BY `pretixbase_order`.`datetime` DESC LIMIT 1

**Comment by RincewindWizzard** [comment]
You can fix this error by excecuting following SQL statement:

    SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

via [Stackoverflow](https://stackoverflow.com/questions/23921117/disable-only-full-group-by)

**Comment by raphaelm** [comment]
Good to know. Is it enough if you execute that once (as in: does it work for you now) or would that need to be executed in every connection?

I'm wondering why my MySQL installations are not running into the issue, what MySQL version do you run?

However, that query will change in 1.7 again an, so I will look out for this.

**Comment by RincewindWizzard** [comment]
The MySQL server version is "5.7.19-0ubuntu0.16.04.1 - (Ubuntu)".
I executed the above once and had no error since.

**Comment by raphaelm** [comment]
Okay, since this appears to be a default setting in mysql 5.7.5+ we should maybe fix this nevertheless. In MariaDB it apparently is not.

**Comment by rkhyd** [comment]
hello raphaelm,
i have set the mysqlmode as specified in the thread. The attendees tab still shows the "Internal Server Error". The error log shows this
`django.db.utils.OperationalError: (1055, "Expression #22 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pretix.pretixbase_invoiceaddress.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")'
The tab is working for other events, but not for a particular event. What could be the issue.

**Comment by raphaelm** [comment]
The error message pretty clearly says that SQL mode ``only_full_group_by`` is still active. I'm not an expert on MySQL modes.
