### ISSUE TITLE
Creating testdata behaves weird on docker container

### ISSUE THREAD

**Issue by koebi** [pretix/pretix#651]
I first set up a docker image using `docker build .` on my local checkout (which has some data, events and organizers in it) and ran it. Although I had no access to any organizers, events and whatsoever, the `python make_testdata.py`-command told me that "There already is data in your DB!"

Then I started a container using `docker run pretix/standalone:stable` and tried the `python make_testdata.py`-command, which led to a huge pile of errors:

```
pretixuser@ef87669093b2:~/src$ python3 make_testdata.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: pretixbase_organizer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "make_testdata.py", line 15, in <module>
    if Organizer.objects.exists():
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 670, in exists
    return self.query.has_results(using=self.db)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 517, in has_results
    return compiler.has_results()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 853, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 884, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: pretixbase_organizer
```

I don't really know what to make of this, but none of the two behaviours seem right, so I thought I'd file an Issue :)

**Comment by raphaelm** [comment]
``make_testdata`` no longer exists
