### ISSUE TITLE
Update from 1.12.2 to 1.13.1 migration failing

### ISSUE THREAD

**Issue by bobapple** [pretix/pretix#844]
I can successfully update from `1.12.2` to `1.13.1` with pip. However, when I run the DB migration, something is failing:

``` shell
root@localhost:~# python3 -m pretix migrate
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'pretix' has no attribute 'multidomain'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pretix/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/pretix/multidomain/__init__.py", line 2, in <module>
    from django.urls import RegexURLPattern
ImportError: cannot import name 'RegexURLPattern'
```

I am using the following versions:
Ubuntu 16.04

pretix (1.13.1)
pretix-fontpack-free (1.0.2.post1)
pretix-pages (1.2.2)
pretix-passbook (1.3.0)
pretix-sepadebit (1.2.2)
pretix-wirecard (0.5.2)

As a workaround I downgraded to 1.12.1. Please let me know if I can provide any more information

**Comment by raphaelm** [comment]
Sounds like you have a wrong Django version (2.0 instead of 1.11) installed. Why aren't you using a virtual environment to isolate your version dependencies, as recommended by our development docs? :)

**Comment by bobapple** [comment]
Wow, thank you for the tremendously fast response! The installation is already isolated in a virtual machine and it's easier for our configuration management to handle it like this. But yes, in general I would agree :)

You're right regarding the Django version, it was updated without intention. Thank you!
