### ISSUE TITLE
Missing invoice after cancellation

### ISSUE THREAD

**Issue by bobapple** [pretix/pretix#913]
I have an order that has been cancelled. The invoice for the cancellation is available and can be downloaded. The initial invoice of the order is not available to be downloaded. It is also missing on the filesystem:

```
May 16 13:17:05 localhost gunicorn[24714]: ERROR 2018-05-16 13:17:05,558 django.request exception Internal Server Error: /control/event/ORG/foo/invoice/581
May 16 13:17:05 localhost gunicorn[24714]: Traceback (most recent call last):
May 16 13:17:05 localhost gunicorn[24714]:   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
May 16 13:17:05 localhost gunicorn[24714]:     response = get_response(request)
May 16 13:17:05 localhost gunicorn[24714]:   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
May 16 13:17:05 localhost gunicorn[24714]:     response = self.process_exception_by_middleware(e, request)
May 16 13:17:05 localhost gunicorn[24714]:   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
May 16 13:17:05 localhost gunicorn[24714]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
May 16 13:17:05 localhost gunicorn[24714]:   File "/usr/local/lib/python3.5/dist-packages/pretix/control/permissions.py", line 27, in wrapper
May 16 13:17:05 localhost gunicorn[24714]:     return function(request, *args, **kw)
May 16 13:17:05 localhost gunicorn[24714]:   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 68, in view
May 16 13:17:05 localhost gunicorn[24714]:     return self.dispatch(request, *args, **kwargs)
May 16 13:17:05 localhost gunicorn[24714]:   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 88, in dispatch
May 16 13:17:05 localhost gunicorn[24714]:     return handler(request, *args, **kwargs)
May 16 13:17:05 localhost gunicorn[24714]:   File "/usr/local/lib/python3.5/dist-packages/pretix/control/views/orders.py", line 464, in get
May 16 13:17:05 localhost gunicorn[24714]:     resp = FileResponse(self.invoice.file.file, content_type='application/pdf')
May 16 13:17:05 localhost gunicorn[24714]:   File "/usr/local/lib/python3.5/dist-packages/django/db/models/fields/files.py", line 51, in _get_file
May 16 13:17:05 localhost gunicorn[24714]:     self._file = self.storage.open(self.name, 'rb')
May 16 13:17:05 localhost gunicorn[24714]:   File "/usr/local/lib/python3.5/dist-packages/django/core/files/storage.py", line 38, in open
May 16 13:17:05 localhost gunicorn[24714]:     return self._open(name, mode)
May 16 13:17:05 localhost gunicorn[24714]:   File "/usr/local/lib/python3.5/dist-packages/django/core/files/storage.py", line 300, in _open
May 16 13:17:05 localhost gunicorn[24714]:     return File(open(self.path(name), mode))
May 16 13:17:05 localhost gunicorn[24714]: FileNotFoundError: [Errno 2] No such file or directory: '/var/pretix/data/media/invoices/ORG/foo/FOO-2018-00082-8PDJU-qUkbH00EJTtaCM6y.pdf'
```

I have older orders with the same scenario (order+cancellation) where both invoices are available. I suspect at some point invoices have not been rendered (maybe a certain pretix version?).

The cancellation invoice can be regenerated. Is there any way how I can re-generate the initial invoice?

**Comment by raphaelm** [comment]
Hmm, this is weird, and the fact that the file is missing shouldn't be related to the fact that the order is canceled.

There are edgecases where an invoice is created in the database but no PDFs are generated. In that case, the PDF is generated when you try to download the invoice for the first time. In this case however, the PDF must have been generated at some point – otherwise there would be no filename in the database and you wouldn't get this error message.

The easiest way to generate a new PDF is probably to clear the filename from the database for this invoice, this way the invoice will be re-rendered once you try to download it again.

**Comment by bobapple** [comment]
So I found out that this happens in the current version `1.15.1` and only after an order is cancelled the initial invoice disappears.

Setting `file=NULL` directly in the database helps, the invoice is regenerated. Is there any information I could provide to help?

**Comment by raphaelm** [comment]
Found the bug and fixed in  https://github.com/pretix/pretix/commit/d65d48db48ccdc50e455238d9e81d434c02d96bc
