### ISSUE TITLE
Pretix background unable to start: `KeyError: 'async'`

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#932]
The background worker is currently unable to start with the following error:

```
May 30 08:54:45 pretix celery[3953]: Traceback (most recent call last):
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/kombu/transport/base.py", line 123, in __getattr__
May 30 08:54:45 pretix celery[3953]:     return self[key]
May 30 08:54:45 pretix celery[3953]: KeyError: 'async'
May 30 08:54:45 pretix celery[3953]: During handling of the above exception, another exception occurred:
May 30 08:54:45 pretix celery[3953]: Traceback (most recent call last):
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/bin/celery", line 11, in <module>
May 30 08:54:45 pretix celery[3953]:     sys.exit(main())
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
May 30 08:54:45 pretix celery[3953]:     _main()
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
May 30 08:54:45 pretix celery[3953]:     cmd.execute_from_commandline(argv)
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
May 30 08:54:45 pretix celery[3953]:     super(CeleryCommand, self).execute_from_commandline(argv)))
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
May 30 08:54:45 pretix celery[3953]:     return self.handle_argv(self.prog_name, argv[1:])
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
May 30 08:54:45 pretix celery[3953]:     return self.execute(command, argv)
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
May 30 08:54:45 pretix celery[3953]:     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
May 30 08:54:45 pretix celery[3953]:     return self(*args, **options)
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
May 30 08:54:45 pretix celery[3953]:     ret = self.run(*args, **kwargs)
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/celery/bin/worker.py", line 255, in run
May 30 08:54:45 pretix celery[3953]:     **kwargs)
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/celery/worker/worker.py", line 99, in __init__
May 30 08:54:45 pretix celery[3953]:     self.setup_instance(**self.prepare_args(**kwargs))
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/celery/worker/worker.py", line 122, in setup_instance
May 30 08:54:45 pretix celery[3953]:     self.should_use_eventloop() if use_eventloop is None
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
May 30 08:54:45 pretix celery[3953]:     self._conninfo.transport.implements.async and
May 30 08:54:45 pretix celery[3953]:   File "/var/pretix/venv/lib/python3.6/site-packages/kombu/transport/base.py", line 125, in __getattr__
May 30 08:54:45 pretix celery[3953]:     raise AttributeError(key)
May 30 08:54:45 pretix celery[3953]: AttributeError: async
```

The pretix version is 1.15.2.

Any hints on how to correct or debug this more?

**Comment by raphaelm** [comment]
Please check what versions of celery and kombu you have (see #921), you need kombu >= 4.2.0. This should be fixed as per dependency changes in 1.15.2, so maybe your update to 1.15.2 didn't pull in the latest dependencies?

**Comment by thegcat** [comment]
Thank you for your prompt help!

I had kombu 4.2.0 and celery 4.1.0 and I had also checked that everything was up-to-date with pip3. It seems having kombu 4.2.0 requires having celery 4.1.1, which the `requirements.txt` does not guarantee https://github.com/pretix/pretix/blob/master/src/requirements/production.txt#L19

Updating celery fixed the issue, but as this was not enforced by any requirements I feel this is a bug.

**Comment by raphaelm** [comment]
You are correct. Fixed now, but I probably won't issue a bugfix release since 1.16 comes soon anyways.

**Comment by thegcat** [comment]
Thanks.

We're good for now, so we won't need the bugfix release :-) If you don't have tens more users stumbling over this waiting for the next release is probably fine.
