### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by morfestboy** [pretix/pretix#968]
Hello 

I host this project on our server.
Sometime i got error look like this.

```
ERROR 2018-07-23 05:14:21,565 django.request exception Internal Server Error: /control/event/myproject/test01/settings/payment
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/var/pretix/venv/lib/python3.5/site-packages/pretix/control/middleware.py", line 68, in process_request
    if not request.user.is_authenticated:
  File "/var/pretix/venv/lib/python3.5/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/var/pretix/venv/lib/python3.5/site-packages/django/utils/functional.py", line 386, in _setup
    self._wrapped = self._setupfunc()
  File "/var/pretix/venv/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/var/pretix/venv/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 218, in get_user
    user = backend.get_user(user_id)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/contrib/auth/backends.py", line 102, in get_user
    user = UserModel._default_manager.get(pk=user_id)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2013, 'Lost connection to MySQL server during query')
ERROR 2018-07-23 05:14:21,565 django.request exception Internal Server Error: /control/event/myproject/test01/settings/payment
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/var/pretix/venv/lib/python3.5/site-packages/pretix/control/middleware.py", line 68, in process_request
    if not request.user.is_authenticated:
  File "/var/pretix/venv/lib/python3.5/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/var/pretix/venv/lib/python3.5/site-packages/django/utils/functional.py", line 386, in _setup
    self._wrapped = self._setupfunc()
  File "/var/pretix/venv/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/var/pretix/venv/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 218, in get_user
    user = backend.get_user(user_id)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/contrib/auth/backends.py", line 102, in get_user
    user = UserModel._default_manager.get(pk=user_id)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/pretix/venv/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/var/pretix/venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2013, 'Lost connection to MySQL server during query')
```

How to fix this?
This is some MySQL information. (I use on Amazon RDS Aurora)

version : 5.7.12
version_comment : MySQL Community Server (GPL)
version_compile_machine : x86_64
version_compile_os : Linux
max_allowed_packet : 1073741824
wait_timeout : 28800

**Comment by raphaelm** [comment]
That is some problem with your database (Amazon RDS) or network setup, somehow the connection to the MySQL server is lost in process. I can't tell you more, as I don't know your setup, and it's not a bug in pretix.
