### ISSUE TITLE
no emails are sent

### ISSUE THREAD

**Issue by jeyca** [pretix/pretix#971]
I installed succesfully pretix on a shared webhost (uberspace.de), but the only problem is, that it looks like the installation is not able to send an email. I just did a test buy and did not get a confirmation mail. I first tried without any email config and then set login datas to an email account like:

```
[mail]
from=user@domain.tld
host=mx2f47.netcup.net
user=pretix
password=password
port=143
admins=admin@domain.tld
tls=on
ssl=off
```
but it also did not work out. There was an error message in the logs, but I can't find how to fix that:

```
ERROR 2018-07-24 18:33:18,076 pretix.base.mail mail Error sending email
Traceback (most recent call last):
  File "/home/user/src/pretix/code/src/pretix/base/services/mail.py", line 210, in mail_send_task
	backend.send_messages([email])
  File "/home/user/src/pretix/lib64/python3.6/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
	new_conn_created = self.open()
  File "/home/user/src/pretix/lib64/python3.6/site-packages/django/core/mail/backends/smtp.py", line 64, in open
	self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib64/python3.6/smtplib.py", line 254, in init
	raise SMTPConnectError(code, msg)
smtplib.SMTPConnectError: (-1, b'[CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.')
ERROR 2018-07-24 18:33:18,077 celery.app.trace trace Task pretix.base.services.mail.mail_send_task[88cd1c2d-45ca-40c3-a8f9-64f26dd1a30b] raised unexpected: SendMailException("Failed to send an email to ['testuser@mail.com'].",)
Traceback (most recent call last):
  File "/home/user/src/pretix/code/src/pretix/base/services/mail.py", line 210, in mail_send_task
	backend.send_messages([email])
  File "/home/user/src/pretix/lib64/python3.6/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
	new_conn_created = self.open()
  File "/home/user/src/pretix/lib64/python3.6/site-packages/django/core/mail/backends/smtp.py", line 64, in open
	self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib64/python3.6/smtplib.py", line 254, in init
	raise SMTPConnectError(code, msg)
smtplib.SMTPConnectError: (-1, b'[CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/src/pretix/lib64/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
	R = retval = fun(*args, **kwargs)
  File "/home/user/src/pretix/code/src/pretix/base/services/mail.py", line 213, in mail_send_task
	raise SendMailException('Failed to send an email to {}.'.format(to))
pretix.base.services.mail.SendMailException: Failed to send an email to ['testuser@mail.com'].
INFO 2018-07-24 18:33:18,081 celery.app.trace trace Task pretix.base.services.orders.perform_order[cf56aac4-1d99-4238-a842-660519578e01] succeeded in 0.23219488200265914s: 1
INFO 2018-07-24 18:33:18,455 celery.app.trace trace Task pretix.base.services.notifications.notify[10c38041-fbeb-472f-9086-48cbc352379e] succeeded in 0.020446636015549302s: None
```

**Comment by pc-coholic** [comment]
Unless you are using custom ports on your Mailserver, port 143 is IMAP.

You might need to put the right port for your SMTP-server.

**Comment by raphaelm** [comment]
What martin says :)
